#!/usr/bin/env node
/**
 * The AIA skin over the 18.6.6 interface (ADR 0013):
 *   src/design/tokens.json + src/skin/legacy-variables.json + src/skin/components.css
 *     → public/skin/skin.css
 *
 * Four layers, in this order:
 *   1. @font-face for the self-hosted faces (faces.mjs, shared with AIA's pages);
 *   2. the design system's tokens, prefixed `--aia-`, because 18.6.6 already uses
 *      some of the same names (`--ink`, `--space-*`) with different values;
 *   3. the variable layer: each 18.6.6 custom property re-pointed at a token,
 *      from legacy-variables.json;
 *   4. the hand-written component rules, which may use only `var(...)` for
 *      colour, radius, shadow and font. `lintComponents` enforces that.
 *
 * Light only, and deliberately so: see legacy-variables.json `meta.theme`.
 * `--check` regenerates in memory and exits 1 if the committed file differs.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { fontFaceCss } from "./faces.mjs";
import { lintComponents } from "./skin-lint.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "public/skin/skin.css");
const tokens = JSON.parse(readFileSync(join(root, "src/design/tokens.json"), "utf8"));
const mapping = JSON.parse(readFileSync(join(root, "src/skin/legacy-variables.json"), "utf8"));
const components = readFileSync(join(root, "src/skin/components.css"), "utf8");
const legacyDocument = readFileSync(join(root, "../../legacy/npc-panel-18.6.6/app/ui_app.html"), "utf8");

const THEME = "light";
const colors = new Map(tokens.color.tokens.map((t) => [t.name, t]));
function resolveColor(name, depth = 0) {
  const t = colors.get(name);
  if (!t) throw new Error(`no colour token ${name}`);
  if (depth > 16) throw new Error(`alias chain too deep at ${name}`);
  const v = typeof t.value === "string" ? t.value : t.value[THEME];
  return /^\{[A-Za-z0-9_.-]+\}$/.test(v) ? resolveColor(v.slice(1, -1), depth + 1) : v;
}
const scalar = (family, name) => {
  const t = (tokens[family]?.tokens ?? []).find((x) => x.name === name);
  if (!t) throw new Error(`no ${family} token ${name}`);
  return t.value;
};

// ---- 2. tokens, prefixed ---------------------------------------------------
const tokenDecls = [
  ...tokens.color.tokens.map((t) => `  --aia-${t.name}: ${resolveColor(t.name)};`),
  ...(tokens.shadow?.tokens ?? []).map((t) => `  --aia-${t.name}: ${typeof t.value === "string" ? t.value : t.value[THEME]};`),
  ...["spacing", "radius", "stroke", "duration"].flatMap((f) => (tokens[f]?.tokens ?? []).map((t) => `  --aia-${t.name}: ${t.value};`)),
  ...Object.entries(tokens.type.families).map(([key, stack]) => `  --aia-font-${key}-stack: ${stack};`),
];

// ---- 3. the variable layer -------------------------------------------------
const definedInLegacy = (name) => legacyDocument.includes(`${name}:`) || legacyDocument.includes(`var(${name}`);
const variableDecls = mapping.map.map((m) => {
  if (!definedInLegacy(m.var)) throw new Error(`legacy-variables.json maps ${m.var}, which ui_app.html never defines or uses`);
  if (!m.why) throw new Error(`legacy-variables.json: ${m.var} has no reason`);
  let value;
  if (m.token) value = `var(--aia-${(resolveColor(m.token), m.token)})`;
  else if (m.radius) value = `var(--aia-${(scalar("radius", m.radius), m.radius)})`;
  else if (m.font) {
    if (!tokens.type.families[m.font]) throw new Error(`no type family ${m.font}`);
    value = `var(--aia-font-${m.font}-stack)`;
  } else if (m.value === "none") value = "none";
  else throw new Error(`legacy-variables.json: ${m.var} needs token, radius, font or value "none"`);
  return `  ${m.var}: ${value};`;
});

// ---- 4. component rules, linted --------------------------------------------

const problems = lintComponents(components);
if (problems.length) {
  console.error(`skin: components.css introduces raw values:\n  ${problems.join("\n  ")}`);
  process.exit(1);
}
const importantCount = (components.replace(/\/\*[\s\S]*?\*\//g, "").match(/!important/g) ?? []).length;

const header = "/* GENERATED by scripts/build-skin.mjs from src/design/tokens.json, src/skin/legacy-variables.json and src/skin/components.css — do not edit by hand. The AIA skin over the 18.6.6 interface (ADR 0013); light only. */";
const css = [
  header,
  "",
  ...fontFaceCss(),
  "",
  `:root {\n  color-scheme: light;\n${tokenDecls.join("\n")}\n}`,
  "",
  "/* 18.6.6's own variables, re-pointed at the design system (src/skin/legacy-variables.json). */",
  `:root {\n${variableDecls.join("\n")}\n}`,
  "",
  components.trim(),
  "",
].join("\n");

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(OUT, "utf8"); } catch { /* missing counts as stale */ }
  if (current !== css) {
    console.error("skin: public/skin/skin.css is stale or hand-edited. Run: npm run skin");
    process.exit(1);
  }
  console.log(`skin: up to date (${variableDecls.length} 18.6.6 variables mapped, ${importantCount} !important)`);
} else {
  writeFileSync(OUT, css);
  console.log(`skin: wrote public/skin/skin.css (${variableDecls.length} 18.6.6 variables mapped, ${importantCount} !important)`);
}
