#!/usr/bin/env node
/**
 * tokens.json → src/app/tokens.css + src/app/tokens-theme.css + src/app/fonts.css + src/design/tokens.ts
 *
 * The repository generator is authoritative. `node scripts/build-tokens.mjs --check`
 * regenerates in memory and exits 1 if either committed file differs, so a
 * hand-edited output or a stale one fails CI.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "src/design/tokens.json");
const CSS = join(root, "src/app/tokens.css");
const TS = join(root, "src/design/tokens.ts");
const THEME = join(root, "src/app/tokens-theme.css");
const FONTS = join(root, "src/app/fonts.css");

/**
 * The self-hosted faces, served from public/skin/fonts/ at /skin/fonts/. One list:
 * AIA's own pages import the generated fonts.css, and the 18.6.6 interface skin
 * (ADR 0013) is built from the same entries. The family names must match the
 * first entry of each stack in tokens.type.families.
 */
const FACES = [
  { family: "IBM Plex Sans", file: "IBMPlexSans-Regular.woff2", weight: 400, style: "normal" },
  { family: "IBM Plex Sans", file: "IBMPlexSans-Italic.woff2", weight: 400, style: "italic" },
  { family: "IBM Plex Sans", file: "IBMPlexSans-Medium.woff2", weight: 500, style: "normal" },
  { family: "IBM Plex Sans", file: "IBMPlexSans-SemiBold.woff2", weight: 600, style: "normal" },
  { family: "IBM Plex Mono", file: "IBMPlexMono-Regular.woff2", weight: 400, style: "normal" },
  { family: "IBM Plex Mono", file: "IBMPlexMono-Medium.woff2", weight: 500, style: "normal" },
  { family: "Source Serif 4", file: "SourceSerif4-Regular.woff2", weight: 400, style: "normal" },
  { family: "Source Serif 4", file: "SourceSerif4-Italic.woff2", weight: 400, style: "italic" },
  { family: "Source Serif 4", file: "SourceSerif4-Semibold.woff2", weight: 600, style: "normal" },
  { family: "Source Serif 4 Display", file: "SourceSerif4Display-Semibold.woff2", weight: 600, style: "normal" },
];
const FONT_URL_BASE = "/skin/fonts/";
for (const f of FACES) {
  if (!existsSync(join(root, "public/skin/fonts", f.file))) throw new Error(`FACES names ${f.file}, which is not in public/skin/fonts/`);
}

const tokens = JSON.parse(readFileSync(SRC, "utf8"));
const themes = tokens.color.themes.map((t) => t.id);
const [first, second] = themes;
if (themes.length !== 2 || first !== "light" || second !== "dark") throw new Error("expected themes [light, dark]");

const byName = new Map(tokens.color.tokens.map((t) => [t.name, t]));
const valueIn = (tok, theme) => (typeof tok.value === "string" ? tok.value : tok.value[theme] ?? tok.value[first]);
const isAlias = (v) => /^\{[A-Za-z0-9_.-]+\}$/.test(v);
function resolve(name, theme, depth = 0) {
  if (depth > 16) throw new Error(`alias chain too deep at ${name}`);
  const tok = byName.get(name);
  if (!tok) throw new Error(`alias to missing token ${name}`);
  const v = valueIn(tok, theme);
  return isAlias(v) ? resolve(v.slice(1, -1), theme, depth + 1) : v;
}
const cssValue = (v) => (isAlias(v) ? `var(--${v.slice(1, -1)})` : v);

const colorDecls = (theme) =>
  tokens.color.tokens.map((t) => `  --${t.name}: ${cssValue(valueIn(t, theme))};`).concat(
    (tokens.shadow?.tokens ?? []).map((t) => `  --${t.name}: ${typeof t.value === "string" ? t.value : t.value[theme] ?? t.value[first]};`),
  );

const scalarFamilies = ["spacing", "radius", "stroke", "density", "duration", "zIndex"];
const scalarDecls = scalarFamilies.flatMap((f) => (tokens[f]?.tokens ?? []).map((t) => `  --${t.name}: ${t.value};`));
const fontDecls = Object.entries(tokens.type.families).map(([key, stack]) => `  --font-${key}-stack: ${stack};`);
const declaredFamilies = new Set(FACES.map((f) => f.family));
for (const [key, stack] of Object.entries(tokens.type.families)) {
  const first = stack.split(",")[0].trim().replace(/^"|"$/g, "");
  if (!declaredFamilies.has(first)) throw new Error(`type.families.${key} starts with "${first}", which no FACES entry provides`);
}

const typeClasses = tokens.type.groups.flatMap((g) =>
  g.styles.map((s) => {
    const fam = s.family ?? g.family;
    const lines = [`font-family: var(--font-${fam}-stack)`, `font-size: ${s.fontSize}`, `line-height: ${s.lineHeight}`, `font-weight: ${s.fontWeight}`];
    if (s.letterSpacing) lines.push(`letter-spacing: ${s.letterSpacing}`);
    return `.type-${s.name} { ${lines.join("; ")}; }`;
  }),
);

const header = "/* GENERATED by scripts/build-tokens.mjs from src/design/tokens.json — do not edit by hand. */";
const css = [
  header,
  "",
  `:root,\n[data-theme="light"] {\n  color-scheme: light;\n${colorDecls("light").join("\n")}\n}`,
  "",
  `[data-theme="dark"] {\n  color-scheme: dark;\n${colorDecls("dark").join("\n")}\n}`,
  "",
  "/* \"System\" theme: no data-theme attribute, follow the OS. */",
  `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n    color-scheme: dark;\n${colorDecls("dark").map((l) => "  " + l).join("\n")}\n  }\n}`,
  "",
  `:root {\n${scalarDecls.concat(fontDecls).join("\n")}\n}`,
  "",
  ...typeClasses,
  "",
].join("\n");

const themeCss = [
  header,
  "/* Tailwind utilities onto the runtime custom properties: bg-surface, text-ink, border-border-strong… */",
  "@theme inline {",
  ...tokens.color.tokens.map((t) => `  --color-${t.name}: var(--${t.name});`),
  ...Object.keys(tokens.type.families).map((k) => `  --font-${k}: var(--font-${k}-stack);`),
  // Literal values, not var(): a token that pointed at a custom property of the
  // same name would be a self-reference and resolve to nothing.
  ...(tokens.radius?.tokens ?? []).map((t) => `  --${t.name}: ${t.value};`),
  "}",
  "",
].join("\n");

const fontsCss = [
  header,
  "/* Self-hosted faces (SIL OFL 1.1; licences beside the files in public/skin/fonts/). */",
  ...FACES.map((f) => `@font-face { font-family: "${f.family}"; src: url("${FONT_URL_BASE}${f.file}") format("woff2"); font-weight: ${f.weight}; font-style: ${f.style}; font-display: swap; }`),
  "",
].join("\n");

const resolved = {};
for (const t of tokens.color.tokens) resolved[t.name] = { light: resolve(t.name, "light"), dark: resolve(t.name, "dark") };
const ts = `${header.replace("/*", "//").replace(" */", "")}

/** Resolved colour values per theme, for JavaScript consumers (charts, canvas). CSS uses the custom properties. */
export const colors = ${JSON.stringify(resolved, null, 2)} as const;

export type ColorToken = keyof typeof colors;
export type Theme = "light" | "dark";

/** The CSS custom property for a colour token, e.g. cssVar("ink") → "var(--ink)". */
export function cssVar(name: ColorToken): string {
  return \`var(--\${name})\`;
}

export const scalars = ${JSON.stringify(Object.fromEntries(scalarFamilies.flatMap((f) => (tokens[f]?.tokens ?? []).map((t) => [t.name, t.value]))), null, 2)} as const;
`;

if (process.argv.includes("--check")) {
  const drift = [[CSS, css], [TS, ts], [THEME, themeCss], [FONTS, fontsCss]].filter(([p, want]) => {
    try { return readFileSync(p, "utf8") !== want; } catch { return true; }
  });
  if (drift.length) {
    console.error(`tokens: generated files are stale or hand-edited: ${drift.map(([p]) => p.replace(root + "/", "")).join(", ")}\nRun: npm run tokens`);
    process.exit(1);
  }
  console.log(`tokens: up to date (${tokens.color.tokens.length} colours × ${themes.length} themes)`);
} else {
  writeFileSync(CSS, css);
  writeFileSync(TS, ts);
  writeFileSync(THEME, themeCss);
  writeFileSync(FONTS, fontsCss);
  console.log(`tokens: wrote src/app/tokens.css, src/app/tokens-theme.css, src/app/fonts.css and src/design/tokens.ts (${tokens.color.tokens.length} colours × ${themes.length} themes)`);
}
