#!/usr/bin/env node
/**
 * tokens.json → src/app/tokens.css + src/app/tokens-theme.css + src/app/fonts.css + src/design/tokens.ts
 *   + packages/aia_core/src/aia_core/domain/report/print_tokens.py (the DOCX report's print register)
 *
 * The repository generator is authoritative. `node scripts/build-tokens.mjs --check`
 * regenerates in memory and exits 1 if either committed file differs, so a
 * hand-edited output or a stale one fails CI.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "src/design/tokens.json");
const CSS = join(root, "src/app/tokens.css");
const TS = join(root, "src/design/tokens.ts");
const THEME = join(root, "src/app/tokens-theme.css");
const FONTS = join(root, "src/app/fonts.css");

import { FACES, fontFaceCss } from "./faces.mjs";

const tokens = JSON.parse(readFileSync(SRC, "utf8"));
const themes = tokens.color.themes.map((t) => t.id);
const [first, second] = themes;
if (themes.length !== 2 || first !== "light" || second !== "dark") throw new Error("expected themes [light, dark]");

const byName = new Map(tokens.color.tokens.map((t) => [t.name, t]));
const valueIn = (tok, theme) => (typeof tok.value === "string" ? tok.value : tok.value[theme] ?? tok.value[first]);
const isAlias = (v) => /^\{[A-Za-z0-9_.-]+\}$/.test(v);
function resolve(name, theme, depth = 0) {
  if (depth > 16) throw new Error(`alias chain too deep at ${name}`);
  const tok = byName.get(name);
  if (!tok) throw new Error(`alias to missing token ${name}`);
  const v = valueIn(tok, theme);
  return isAlias(v) ? resolve(v.slice(1, -1), theme, depth + 1) : v;
}
const cssValue = (v) => (isAlias(v) ? `var(--${v.slice(1, -1)})` : v);

const colorDecls = (theme) =>
  tokens.color.tokens.map((t) => `  --${t.name}: ${cssValue(valueIn(t, theme))};`).concat(
    (tokens.shadow?.tokens ?? []).map((t) => `  --${t.name}: ${typeof t.value === "string" ? t.value : t.value[theme] ?? t.value[first]};`),
  );

const scalarFamilies = ["spacing", "radius", "stroke", "density", "duration", "zIndex"];
const scalarDecls = scalarFamilies.flatMap((f) => (tokens[f]?.tokens ?? []).map((t) => `  --${t.name}: ${t.value};`));
const fontDecls = Object.entries(tokens.type.families).map(([key, stack]) => `  --font-${key}-stack: ${stack};`);
const declaredFamilies = new Set(FACES.map((f) => f.family));
for (const [key, stack] of Object.entries(tokens.type.families)) {
  const first = stack.split(",")[0].trim().replace(/^"|"$/g, "");
  if (!declaredFamilies.has(first)) throw new Error(`type.families.${key} starts with "${first}", which no FACES entry provides`);
}

const typeClasses = tokens.type.groups.flatMap((g) =>
  g.styles.map((s) => {
    const fam = s.family ?? g.family;
    const lines = [`font-family: var(--font-${fam}-stack)`, `font-size: ${s.fontSize}`, `line-height: ${s.lineHeight}`, `font-weight: ${s.fontWeight}`];
    if (s.letterSpacing) lines.push(`letter-spacing: ${s.letterSpacing}`);
    if (s.fontStyle) lines.push(`font-style: ${s.fontStyle}`);
    return `.type-${s.name} { ${lines.join("; ")}; }`;
  }),
);

const header = "/* GENERATED by scripts/build-tokens.mjs from src/design/tokens.json — do not edit by hand. */";
const css = [
  header,
  "",
  `:root,\n[data-theme="light"] {\n  color-scheme: light;\n${colorDecls("light").join("\n")}\n}`,
  "",
  `[data-theme="dark"] {\n  color-scheme: dark;\n${colorDecls("dark").join("\n")}\n}`,
  "",
  "/* \"System\" theme: no data-theme attribute, follow the OS. */",
  `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n    color-scheme: dark;\n${colorDecls("dark").map((l) => "  " + l).join("\n")}\n  }\n}`,
  "",
  `:root {\n${scalarDecls.concat(fontDecls).join("\n")}\n}`,
  "",
  ...typeClasses,
  "",
].join("\n");

const themeCss = [
  header,
  "/* Tailwind utilities onto the runtime custom properties: bg-surface, text-ink, border-border-strong… */",
  "@theme inline {",
  ...tokens.color.tokens.map((t) => `  --color-${t.name}: var(--${t.name});`),
  ...Object.keys(tokens.type.families).map((k) => `  --font-${k}: var(--font-${k}-stack);`),
  // Literal values, not var(): a token that pointed at a custom property of the
  // same name would be a self-reference and resolve to nothing.
  ...(tokens.radius?.tokens ?? []).map((t) => `  --${t.name}: ${t.value};`),
  "}",
  "",
].join("\n");

const fontsCss = [
  header,
  "/* Self-hosted faces (SIL OFL 1.1; licences beside the files in public/skin/fonts/). */",
  ...fontFaceCss(),
  "",
].join("\n");

const resolved = {};
for (const t of tokens.color.tokens) resolved[t.name] = { light: resolve(t.name, "light"), dark: resolve(t.name, "dark") };
const ts = `${header.replace("/*", "//").replace(" */", "")}

/** Resolved colour values per theme, for JavaScript consumers (charts, canvas). CSS uses the custom properties. */
export const colors = ${JSON.stringify(resolved, null, 2)} as const;

export type ColorToken = keyof typeof colors;
export type Theme = "light" | "dark";

/** The CSS custom property for a colour token, e.g. cssVar("ink") → "var(--ink)". */
export function cssVar(name: ColorToken): string {
  return \`var(--\${name})\`;
}

export const scalars = ${JSON.stringify(Object.fromEntries(scalarFamilies.flatMap((f) => (tokens[f]?.tokens ?? []).map((t) => [t.name, t.value]))), null, 2)} as const;
`;

// ---- Print tokens for the DOCX report (packages/aia_core/.../domain/report/print_tokens.py).
// Pure Python constants, formatted so `ruff format --check` leaves them alone.
const PRINT = join(root, "../../packages/aia_core/src/aia_core/domain/report/print_tokens.py");
const pyStr = (s) => JSON.stringify(s);
const pyNum = (n) => (Number.isInteger(n) ? `${n}.0` : `${n}`);
const pyBool = (b) => (b ? "True" : "False");
function printPy() {
  const p = tokens.print;
  if (!p) throw new Error("tokens.json has no print section");
  const deliverable = tokens.type.groups.find((g) => g.name === "Deliverable");
  const face = (family, weight) => {
    const f = p.faces[family]?.[String(weight)];
    if (!f) throw new Error(`print.faces has no ${family} ${weight}`);
    return f;
  };
  const colorNames = [
    ...p.colors,
    ...tokens.color.tokens.map((t) => t.name).filter((n) => p.colorPrefixes.some((pre) => n.startsWith(pre))),
  ];
  for (const n of colorNames) if (!byName.has(n)) throw new Error(`print.colors names missing token ${n}`);
  const styles = deliverable.styles.map((s) => {
    if (!s.print) throw new Error(`Deliverable style ${s.name} has no print metrics`);
    const family = s.family ?? deliverable.family;
    const f = face(family, s.fontWeight);
    const q = s.print;
    return [
      `    ${pyStr(s.name)}: PrintStyle(`,
      `        name=${pyStr(s.name)},`,
      `        font=${pyStr(f.font)},`,
      `        family=${pyStr(family)},`,
      `        bold=${pyBool(!!f.bold)},`,
      `        italic=${pyBool(s.fontStyle === "italic")},`,
      `        size_pt=${pyNum(q.size)},`,
      `        leading_pt=${pyNum(q.leading)},`,
      `        before_pt=${pyNum(q.before)},`,
      `        after_pt=${pyNum(q.after)},`,
      `        caps=${pyBool(!!q.caps)},`,
      `        tracking_pt=${pyNum(q.tracking ?? 0)},`,
      `    ),`,
    ].join("\n");
  });
  const fonts = [...new Set(Object.values(p.faces).flatMap((w) => Object.values(w).map((f) => f.font)))];
  return `"""GENERATED by apps/web/scripts/build-tokens.mjs from apps/web/src/design/tokens.json.

Do not edit by hand: \`npm run tokens:check\` fails CI on drift. The print register of
the design system for the DOCX report — the light theme's colours (a report is
paper even when the Studio is dark), the Deliverable type group in points, and the
page geometry. Pure constants: importable with nothing installed but the stdlib.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True)
class PrintStyle:
    """One Deliverable type style, resolved to a Word font and point metrics."""

    name: str
    font: str
    family: str
    bold: bool
    italic: bool
    size_pt: float
    leading_pt: float
    before_pt: float
    after_pt: float
    caps: bool
    tracking_pt: float


@dataclass(frozen=True)
class PageGeometry:
    """A4 portrait, in millimetres. Inside/outside margins mirror on facing pages."""

    width_mm: float
    height_mm: float
    margin_top_mm: float
    margin_bottom_mm: float
    margin_inside_mm: float
    margin_outside_mm: float
    header_mm: float
    footer_mm: float


PAGE: Final = PageGeometry(
    width_mm=${pyNum(p.page.widthMm)},
    height_mm=${pyNum(p.page.heightMm)},
    margin_top_mm=${pyNum(p.page.marginTopMm)},
    margin_bottom_mm=${pyNum(p.page.marginBottomMm)},
    margin_inside_mm=${pyNum(p.page.marginInsideMm)},
    margin_outside_mm=${pyNum(p.page.marginOutsideMm)},
    header_mm=${pyNum(p.page.headerMm)},
    footer_mm=${pyNum(p.page.footerMm)},
)

#: Resolved light-theme colours, \`#rrggbb\`.
COLORS: Final[dict[str, str]] = {
${colorNames.map((n) => `    ${pyStr(n)}: ${pyStr(resolve(n, "light"))},`).join("\n")}
}

#: The Deliverable type group, by style name.
STYLES: Final[dict[str, PrintStyle]] = {
${styles.join("\n")}
}

#: Every Word font name a report may use; each must be embeddable.
FONTS: Final[tuple[str, ...]] = (
${fonts.map((f) => `    ${pyStr(f)},`).join("\n")}
)
`;
}
const printSrc = printPy();

if (process.argv.includes("--check")) {
  const drift = [[CSS, css], [TS, ts], [THEME, themeCss], [FONTS, fontsCss], [PRINT, printSrc]].filter(([p, want]) => {
    try { return readFileSync(p, "utf8") !== want; } catch { return true; }
  });
  if (drift.length) {
    console.error(`tokens: generated files are stale or hand-edited: ${drift.map(([p]) => p.replace(root + "/", "")).join(", ")}\nRun: npm run tokens`);
    process.exit(1);
  }
  console.log(`tokens: up to date (${tokens.color.tokens.length} colours × ${themes.length} themes)`);
} else {
  writeFileSync(CSS, css);
  writeFileSync(TS, ts);
  writeFileSync(THEME, themeCss);
  writeFileSync(FONTS, fontsCss);
  mkdirSync(dirname(PRINT), { recursive: true });
  writeFileSync(PRINT, printSrc);
  console.log(`tokens: wrote src/app/tokens.css, src/app/tokens-theme.css, src/app/fonts.css, src/design/tokens.ts and aia_core domain/report/print_tokens.py (${tokens.color.tokens.length} colours × ${themes.length} themes)`);
}
