"""Native design jobs through the real worker, gateway, adapter and ledger."""

from __future__ import annotations

import dataclasses
import json
from dataclasses import dataclass, field
from typing import Any

import pytest
from aia_core.application.research import ResearchAgentJobs
from aia_core.domain.ai_material import MaterialApproval, material_sha256
from aia_core.domain.design import DesignRejected
from aia_core.domain.prompts import PromptPin
from aia_core.domain.research_agents import (
    BASELINE_PROMPT_VERSION,
    FIXED_PREFIX,
    ResearchAction,
    prompt_for,
)
from aia_core.domain.residency import DataClass
from aia_core.domain.scope import WORKER_PERMISSIONS, ScopeDenied
from aia_core.domain.workflow import WorkflowRunStatus
from aia_core.infrastructure.ai_usage_repository import AIUsageRepository
from aia_core.infrastructure.model_adapters.transport import (
    HttpRequest,
    HttpResponse,
    TransportFailure,
)
from aia_core.infrastructure.prompt_repository import PromptRepository
from aia_core.infrastructure.study_design_repository import StudyDesignRepository
from aia_core.infrastructure.tables import ApprovalDecisionRow, PromptVersionRow
from aia_core.infrastructure.workflow_repository import WorkflowRepository
from aia_executors.ai_runtime import AIRuntimeConfigError, AIRuntimeSettings, build_gateway
from aia_executors.registry import registry_for
from aia_executors.research_agents import ResearchAgentConfig, ResearchAgentExecutor
from aia_worker.settings import WorkerSettings
from aia_worker.worker import Worker
from sqlalchemy import select, update

ANSWER = {
    "title": "Concept",
    "problem_summary": "Test a fictional concept",
    "decision_use": "Launch",
    "objectives": ["Test appeal"],
    "research_questions": ["Why?"],
    "hypotheses": [],
    "recommended_topics": [],
    "tracked_sets": [],
    "non_object_measures": [],
    "questions_for_user": [],
    "complexity": "short",
    "method_reason": "Short study",
    "ready_for_questionnaire": True,
}
DESIGN = {"title": "Fictional concept", "goal": "Test concept", "sections": []}
APPROVAL = MaterialApproval(
    sha256=material_sha256(DESIGN),
    data_class=DataClass.CLASS_C_INTERNAL,
    provenance="generated by this test; no client input",
)


class Signer:
    def sign(self, *, method: str, url: str, headers: Any, body: bytes) -> dict[str, str]:
        return {**dict(headers), "authorization": "AWS4-HMAC-SHA256 test"}


@dataclass
class RecordedBedrock:
    requests: list[HttpRequest] = field(default_factory=list)
    uncertain: bool = False

    async def send(self, request: HttpRequest, *, timeout_s: float) -> HttpResponse:
        self.requests.append(request)
        if self.uncertain:
            from aia_core.domain.ai_contracts import Delivery

            raise TransportFailure("lost response", delivery=Delivery.UNKNOWN)
        tool = request.body["toolConfig"]["tools"][0]["toolSpec"]
        return HttpResponse(
            status=200,
            headers={"x-amzn-requestid": "design-request-1"},
            body={
                "output": {
                    "message": {
                        "role": "assistant",
                        "content": [
                            {
                                "toolUse": {
                                    "toolUseId": "test-tool",
                                    "name": tool["name"],
                                    "input": ANSWER,
                                }
                            }
                        ],
                    }
                },
                "stopReason": "tool_use",
                "usage": {"inputTokens": 900, "outputTokens": 200, "totalTokens": 1100},
            },
        )


def settings(client_id: str, **overrides: str) -> AIRuntimeSettings:
    env = {
        "AIA_ENV": "test",
        "AIA_AI_RUNTIME_ENABLED": "true",
        "AIA_AI_ROUTE_ID": "bedrock-eu-primary",
        "AIA_BEDROCK_REGION": "eu-central-1",
        "AIA_BEDROCK_MODEL_ID": "eu.test-design-v1:0",
        "AIA_AI_POLICY_VERSION": "test-v1",
        "AIA_BEDROCK_INPUT_USD_PER_MTOK": "3",
        "AIA_BEDROCK_OUTPUT_USD_PER_MTOK": "15",
        "AIA_BEDROCK_MAX_OUTPUT_TOKENS": "8192",
        "AIA_BEDROCK_CONTEXT_WINDOW_TOKENS": "200000",
        "AIA_AI_ROUTE_EU_PROCESSING_APPROVED": "true",
        "AIA_AI_ROUTE_EXCLUDED_FROM_TRAINING": "true",
        "AIA_AI_ROUTE_APPROVED_FOR": "CLASS_C_INTERNAL",
        "AIA_AI_FIELDWORK_MAX_OUTPUT_TOKENS": "1024",
        "AIA_AI_FIELDWORK_RESERVATION_USD": "0.25",
        "AIA_AI_RESEARCH_AGENTS_ENABLED": "true",
        "AIA_AI_RESEARCH_MAX_OUTPUT_TOKENS": "8192",
        "AIA_AI_RESEARCH_RESERVATION_USD": "2",
        "AIA_AI_FICTIONAL_CLIENT_IDS": client_id,
        **overrides,
    }
    result = AIRuntimeSettings.from_env(env)
    assert result is not None
    return result


def start(world: Any, *, content: dict[str, Any] | None = None, instruction: str = "") -> str:
    with world.sessions() as session:
        scope = world.lead_scope(session)
        revision, _ = StudyDesignRepository(session, scope).submit(
            content=DESIGN if content is None else content,
            source_stage="brief",
        )
        job = ResearchAgentJobs(session, scope).start(
            design_revision_id=revision.revision_id,
            action=ResearchAction.ANALYZE,
            instruction=instruction,
        )
        session.commit()
        return job.run_id


def worker(
    world: Any,
    database_url: str,
    store: Any,
    build: Any,
    transport: RecordedBedrock,
    *,
    enabled: bool = True,
    fictional: bool = True,
    approvals: tuple[MaterialApproval, ...] = (),
) -> Worker:
    cfg = settings(world.client_id if fictional else "")
    executor = ResearchAgentExecutor(
        store=store,
        build=build,
        gateway=build_gateway(cfg, transport=transport, signer=Signer()) if enabled else None,
        config=ResearchAgentConfig(
            policy_version=cfg.policy_version,
            max_output_tokens=cfg.research_max_output_tokens,
            context_window_tokens=cfg.context_window_tokens,
            reservation_usd=cfg.research_reservation_usd,
            fictional_client_ids=cfg.fictional_client_ids,
            material_approvals=(APPROVAL, *approvals) if fictional else (),
        )
        if enabled
        else None,
    )
    return Worker(
        session_factory=world.sessions,
        executors=registry_for(store=store, build=build, research_agent=executor),
        settings=WorkerSettings(
            database_url=database_url,
            worker_id="design-test",
            executors="aia_executors.registry:build_registry",
            lease_seconds=30,
            heartbeat_seconds=0.1,
            poll_seconds=0.05,
            maintenance_seconds=0.2,
        ),
    )


def test_worker_stores_proposal_and_review_creates_a_new_revision(
    world: Any,
    database_url: str,
    store: Any,
    build: Any,
) -> None:
    run_id = start(world)
    transport = RecordedBedrock()
    w = worker(world, database_url, store, build, transport)
    assert w.run_once()
    assert not w.run_once()
    assert len(transport.requests) == 1
    with world.sessions() as session:
        jobs = ResearchAgentJobs(session, world.lead_scope(session))
        job = jobs.get(run_id)
        assert job["status"] is WorkflowRunStatus.COMPLETED
        payload = jobs.result(run_id, store=store)
        assert payload["provenance"]["provider_request_id"] == "design-request-1"
        assert payload["provenance"]["status"] == "PROPOSED"
        baseline = job["metadata"]["design_revision_id"]
        designs = StudyDesignRepository(session, world.lead_scope(session))
        assert designs.latest().revision_id == baseline
        accepted, created = jobs.accept(run_id, store=store, expected_revision_id=baseline)
        assert created and accepted.parent_revision == 1
        assert designs.content(baseline).get("research_plan") is None
        with pytest.raises(DesignRejected):
            jobs.accept(run_id, store=store, expected_revision_id=baseline)
        session.commit()

        # The accept is one row in the approval ledger (ADR 0019 gate 1, plan 5b.3).
        rows = ledger(session, run_id)
        assert len(rows) == 1
        row = rows[0]
        assert (row.decision, row.gate_type) == ("accept", ResearchAction.ANALYZE.value)
        assert row.artifact_type == "research_agent_proposal"
        assert row.producer_user_id == row.approver_user_id == world.lead_id
        assert row.self_approved is True and row.project_revision == accepted.revision
        assert json.loads(row.comment) == {
            "revision_id": accepted.revision_id,
            "revision_created": True,
            "artifact_id": job["steps"][0]["output"]["artifact_id"],
        }


def ledger(session: Any, run_id: str) -> list[ApprovalDecisionRow]:
    return list(
        session.scalars(
            select(ApprovalDecisionRow).where(
                ApprovalDecisionRow.subject_type == "ai_proposal",
                ApprovalDecisionRow.subject_id == run_id,
            )
        )
    )


def completed_job(world: Any, database_url: str, store: Any, build: Any) -> str:
    run_id = start(world)
    w = worker(world, database_url, store, build, RecordedBedrock())
    assert w.run_once()
    return run_id


def test_a_workers_scope_cannot_accept_an_ai_proposal(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    """ADR 0019 decision 6: the worker holds ``EDIT_STUDY`` but no gate authority."""
    run_id = completed_job(world, database_url, store, build)
    with world.sessions() as session:
        person = world.lead_scope(session)
        as_worker = dataclasses.replace(person, permissions=WORKER_PERMISSIONS)
        baseline = ResearchAgentJobs(session, person).get(run_id)["metadata"]["design_revision_id"]
        with pytest.raises(ScopeDenied) as exc:
            ResearchAgentJobs(session, as_worker).accept(
                run_id, store=store, expected_revision_id=baseline
            )
        assert exc.value.reason == "insufficient_role"
        assert StudyDesignRepository(session, person).latest().revision_id == baseline
        assert ledger(session, run_id) == []


def test_the_same_jobs_accept_is_recorded_once(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    """An unchanged proposal can be accepted again; that is not a second decision."""
    run_id = completed_job(world, database_url, store, build)
    with world.sessions() as session:
        repo = WorkflowRepository(session, world.lead_scope(session))
        fields = {
            "action": ResearchAction.ANALYZE.value,
            "revision_id": "REV-x",
            "project_id": "PRJ-x",
            "project_revision": 2,
            "created": False,
            "artifact_id": "ART-x",
        }
        assert repo.record_ai_proposal_acceptance(run_id, **fields) is True
        assert repo.record_ai_proposal_acceptance(run_id, **fields) is False
        session.commit()
        assert len(ledger(session, run_id)) == 1


@pytest.mark.parametrize("enabled,fictional", [(False, True), (True, False)])
def test_unconfigured_or_confidential_design_never_calls_bedrock(
    world: Any,
    database_url: str,
    store: Any,
    build: Any,
    enabled: bool,
    fictional: bool,
) -> None:
    run_id = start(world)
    transport = RecordedBedrock()
    w = worker(world, database_url, store, build, transport, enabled=enabled, fictional=fictional)
    assert w.run_once()
    assert not w.run_once()
    assert transport.requests == []
    with world.sessions() as session:
        assert (
            ResearchAgentJobs(session, world.lead_scope(session)).get(run_id)["status"]
            is WorkflowRunStatus.WAITING_PROVIDER
        )


def test_unknown_delivery_waits_for_recovery_without_resending(
    world: Any,
    database_url: str,
    store: Any,
    build: Any,
) -> None:
    run_id = start(world)
    transport = RecordedBedrock(uncertain=True)
    w = worker(world, database_url, store, build, transport)
    assert w.run_once()
    assert not w.run_once()
    assert len(transport.requests) == 1
    with world.sessions() as session:
        assert (
            ResearchAgentJobs(session, world.lead_scope(session)).get(run_id)["status"]
            is WorkflowRunStatus.RECOVERY_REQUIRED
        )


@pytest.mark.parametrize(
    "content,instruction",
    [
        ({**DESIGN, "briefing": {"text": "Unclassified pasted client text"}}, ""),
        (
            {
                **DESIGN,
                "briefing": {
                    "attachments": [{"kind": "file", "context_excerpt": "Unknown upload"}]
                },
            },
            "",
        ),
        (DESIGN, "New unclassified client instruction"),
    ],
)
def test_allowlisted_client_cannot_send_unclassified_text(
    world: Any,
    database_url: str,
    store: Any,
    build: Any,
    content: dict[str, Any],
    instruction: str,
) -> None:
    run_id = start(world, content=content, instruction=instruction)
    transport = RecordedBedrock()
    w = worker(world, database_url, store, build, transport)
    assert w.run_once()
    assert not w.run_once()
    assert transport.requests == []
    with world.sessions() as session:
        run = ResearchAgentJobs(session, world.lead_scope(session)).get(run_id)
        assert run["status"] is WorkflowRunStatus.WAITING_PROVIDER
        assert run["steps"][0]["attempts"][-1]["error"]["reason"] == "egress_unclassified_material"


@pytest.mark.parametrize(
    "document",
    [
        "{broken-json}",
        '[{"sha256":"not-a-hash","data_class":"CLASS_C_INTERNAL","provenance":"test"}]',
        "[" + APPROVAL.model_dump_json() + "," + APPROVAL.model_dump_json() + "]",
    ],
)
def test_invalid_material_classification_refuses_runtime_start(document: str) -> None:
    with pytest.raises(AIRuntimeConfigError):
        settings("fictional", AIA_AI_MATERIAL_CLASSIFICATIONS=document)


def test_reservation_must_cover_primary_and_repair_at_verified_prices() -> None:
    with pytest.raises(AIRuntimeConfigError, match="two calls"):
        settings("fictional", AIA_AI_RESEARCH_RESERVATION_USD="0.25")
    with pytest.raises(AIRuntimeConfigError, match="output limit"):
        settings("fictional", AIA_AI_RESEARCH_MAX_OUTPUT_TOKENS="9000")


def test_identical_model_context_does_not_reuse_a_different_revision_baseline(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    first = start(world)
    transport = RecordedBedrock()
    w = worker(world, database_url, store, build, transport)
    assert w.run_once()
    with world.sessions() as session:
        scope = world.lead_scope(session)
        designs = StudyDesignRepository(session, scope)
        baseline = designs.content(designs.latest().revision_id)
        # Provider is deliberately absent from model context, but remains part
        # of the saved project baseline. An old full-project artifact is unsafe.
        revision, _ = designs.submit(
            content={**baseline, "provider": "historical-selection"}, source_stage="brief"
        )
        second = ResearchAgentJobs(session, scope).start(
            design_revision_id=revision.revision_id, action=ResearchAction.ANALYZE
        )
        session.commit()
    assert w.run_once()
    assert len(transport.requests) == 2
    with world.sessions() as session:
        jobs = ResearchAgentJobs(session, world.lead_scope(session))
        first_result = jobs.result(first, store=store)
        second_result = jobs.result(second.run_id, store=store)
        assert (
            first_result["provenance"]["context_sha256"]
            == second_result["provenance"]["context_sha256"]
        )
        assert (
            first_result["provenance"]["design_revision_id"]
            != second_result["provenance"]["design_revision_id"]
        )
        assert second_result["result"]["project"]["provider"] == "historical-selection"


# --------------------------------------------------------------- prompts as data (ADR 0020)

CUSTOM_TASK = "Analyzuj zadání stručně a pouze z dodaných podkladů."
CLIENT_MATERIAL = "Klient Acme plánuje v Q3 zvýšit ceny o 12 % a propustit 40 lidí."


def operator_approves(
    text: str, data_class: DataClass = DataClass.CLASS_C_INTERNAL
) -> MaterialApproval:
    """An operator's classification of a stored prompt's exact text (AIA_AI_MATERIAL_*)."""
    return MaterialApproval(
        sha256=material_sha256(text),
        data_class=data_class,
        provenance="operator review of the prompt",
    )


def put_live(world: Any, prompt_id: str, text: str, *, declared: bool = True) -> None:
    """An administrator saves an edit (declaring it holds no client data) and puts it live.

    ``declared=False`` makes it look like a version saved before declarations existed: the
    rows are what an older deployment left, so no declaration is recorded on them.
    """
    with world.sessions() as session:
        repo = PromptRepository(session, world.admin_context(session))
        version = repo.create_version(prompt_id, text, declares_no_client_data=True)
        if not declared:
            session.execute(
                update(PromptVersionRow)
                .where(
                    PromptVersionRow.prompt_id == prompt_id,
                    PromptVersionRow.version_number == version.version_number,
                )
                .values(declared_class=None, declared_by=None, declared_at=None)
            )
        repo.activate(prompt_id, version.version_number, reason="test")
        session.commit()


def system_sent(transport: RecordedBedrock) -> str:
    return str(transport.requests[0].body["system"][0]["text"])


def test_an_active_edit_is_what_the_model_is_sent_and_what_the_record_names(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    put_live(world, "aia.research.analyze_brief", CUSTOM_TASK)
    run_id = start(world)
    transport = RecordedBedrock()
    # No operator approval: the author's recorded declaration classifies the edit.
    assert worker(world, database_url, store, build, transport).run_once()

    # The code's rails stay in front of whatever the edit says.
    assert system_sent(transport) == FIXED_PREFIX + CUSTOM_TASK
    with world.sessions() as session:
        scope = world.lead_scope(session)
        jobs = ResearchAgentJobs(session, scope)
        assert jobs.get(run_id)["status"] is WorkflowRunStatus.COMPLETED
        provenance = jobs.result(run_id, store=store)["provenance"]
        assert (provenance["prompt_version"], provenance["prompt_origin"]) == ("e1", "stored")
        events = AIUsageRepository(session, scope).events(run_id=run_id)
    assert {e.prompt_version for e in events} == {"e1"}
    import hashlib

    expected = hashlib.sha256(system_sent(transport).encode()).hexdigest()
    assert {e.system_prompt_sha256 for e in events} == {expected}
    assert provenance["prompt_sha256"] == expected


def test_without_an_edit_the_model_is_sent_the_current_code_baseline(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    run_id = start(world)
    transport = RecordedBedrock()
    assert worker(world, database_url, store, build, transport).run_once()
    assert system_sent(transport) == prompt_for(ResearchAction.ANALYZE)
    with world.sessions() as session:
        provenance = ResearchAgentJobs(session, world.lead_scope(session)).result(
            run_id, store=store
        )["provenance"]
    assert (provenance["prompt_version"], provenance["prompt_origin"]) == (
        BASELINE_PROMPT_VERSION,
        "baseline",
    )


def test_a_queued_job_keeps_the_prompt_it_was_queued_with(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    run_id = start(world)  # queued while the code's wording is active
    put_live(world, "aia.research.analyze_brief", CUSTOM_TASK)  # an edit goes live afterwards
    transport = RecordedBedrock()
    assert worker(world, database_url, store, build, transport).run_once()
    assert system_sent(transport) == prompt_for(ResearchAction.ANALYZE)
    with world.sessions() as session:
        job = ResearchAgentJobs(session, world.lead_scope(session)).get(run_id)
    assert job["metadata"]["prompt_origin"] == "baseline"
    # The next job picks up the edit.
    # The same design, queued again: the changed prompt makes it a different job.
    second_id = start(world)
    assert second_id != run_id
    transport2 = RecordedBedrock()
    assert worker(world, database_url, store, build, transport2).run_once()
    assert system_sent(transport2) == FIXED_PREFIX + CUSTOM_TASK


def test_a_draft_runs_only_when_an_administrator_asks_for_it(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    with world.sessions() as session:
        admin = world.admin_context(session)
        PromptRepository(session, admin).create_version(
            "aia.research.analyze_brief", CUSTOM_TASK, declares_no_client_data=True
        )
        revision, _ = StudyDesignRepository(session, world.lead_scope(session)).submit(
            content=DESIGN, source_stage="brief"
        )
        lead_jobs = ResearchAgentJobs(session, world.lead_scope(session))
        with pytest.raises(DesignRejected) as refused:
            lead_jobs.start(
                design_revision_id=revision.revision_id,
                action=ResearchAction.ANALYZE,
                prompt_version=1,
            )
        assert refused.value.reason == "prompt_test_requires_administrator"
        session.rollback()


def test_a_job_whose_pin_was_altered_or_misplaced_is_refused_not_guessed() -> None:
    from aia_executors.research_agents import _pin_of

    analyze = ResearchAction.ANALYZE
    assert _pin_of({}, analyze).origin == "baseline"  # queued before prompts were data
    good = PromptPin.of(
        prompt_id="aia.research.analyze_brief", version="e1", origin="stored", text="a"
    )
    assert _pin_of({"prompt": good.model_dump()}, analyze) == good
    with pytest.raises(ValueError):
        _pin_of({"prompt": {**good.model_dump(), "text": "b"}}, analyze)  # hash mismatch
    with pytest.raises(ValueError):
        _pin_of({"prompt": good.model_dump()}, ResearchAction.CRITIQUE)  # another action's


def test_a_version_saved_before_declarations_existed_is_parked_and_nothing_is_sent(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    """No declaration is not a declaration: such a version has no class, so it is not sent."""
    put_live(world, "aia.research.analyze_brief", CUSTOM_TASK, declared=False)
    run_id = start(world)
    transport = RecordedBedrock()
    assert worker(world, database_url, store, build, transport).run_once()
    assert transport.requests == []
    with world.sessions() as session:
        job = ResearchAgentJobs(session, world.lead_scope(session)).get(run_id)
    assert job["status"] is WorkflowRunStatus.WAITING_PROVIDER


def test_an_operator_can_still_classify_a_version_that_has_no_declaration(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    put_live(world, "aia.research.analyze_brief", CUSTOM_TASK, declared=False)
    run_id = start(world)
    transport = RecordedBedrock()
    approved = (operator_approves(CUSTOM_TASK),)
    assert worker(world, database_url, store, build, transport, approvals=approved).run_once()
    assert system_sent(transport) == FIXED_PREFIX + CUSTOM_TASK
    with world.sessions() as session:
        provenance = ResearchAgentJobs(session, world.lead_scope(session)).result(
            run_id, store=store
        )["provenance"]
    prompt = provenance["material_classification"]["prompt"]
    assert (prompt["source"], prompt["declared_class"], prompt["declared_by"]) == (
        "operator",
        None,
        None,
    )


def test_an_operator_can_classify_a_declared_prompt_as_client_material_and_it_is_not_sent(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    """A declaration is a person's word: the operator's stricter class wins, the route refuses."""
    secret_prompt = f"Analyzuj zadání. Kontext od klienta: {CLIENT_MATERIAL}"
    put_live(world, "aia.research.analyze_brief", secret_prompt)  # declared, then found out
    start(world)
    transport = RecordedBedrock()
    as_client = (operator_approves(secret_prompt, DataClass.CLASS_A_CLIENT_CONFIDENTIAL),)
    assert worker(world, database_url, store, build, transport, approvals=as_client).run_once()
    assert transport.requests == []


def test_a_declared_edit_records_who_declared_it_and_that_the_declaration_classified_it(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    put_live(world, "aia.research.analyze_brief", CUSTOM_TASK)
    run_id = start(world)
    assert worker(world, database_url, store, build, RecordedBedrock()).run_once()
    with world.sessions() as session:
        provenance = ResearchAgentJobs(session, world.lead_scope(session)).result(
            run_id, store=store
        )["provenance"]
    prompt = provenance["material_classification"]["prompt"]
    assert (prompt["origin"], prompt["data_class"], prompt["source"]) == (
        "stored",
        "CLASS_C_INTERNAL",
        "declaration",
    )
    assert prompt["declared_class"] == "CLASS_C_INTERNAL"
    assert prompt["declared_by"] == world.owner_id
    assert prompt["material_sha256"] == material_sha256(CUSTOM_TASK)


def test_a_declaration_and_an_operator_agreeing_is_recorded_as_both(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    put_live(world, "aia.research.analyze_brief", CUSTOM_TASK)
    run_id = start(world)
    approved = (operator_approves(CUSTOM_TASK),)
    assert worker(
        world, database_url, store, build, RecordedBedrock(), approvals=approved
    ).run_once()
    with world.sessions() as session:
        provenance = ResearchAgentJobs(session, world.lead_scope(session)).result(
            run_id, store=store
        )["provenance"]
    assert provenance["material_classification"]["prompt"]["source"] == "declaration+operator"


def test_the_codes_own_wording_needs_no_operator_approval(
    world: Any, database_url: str, store: Any, build: Any
) -> None:
    run_id = start(world)
    assert worker(world, database_url, store, build, RecordedBedrock()).run_once()
    with world.sessions() as session:
        provenance = ResearchAgentJobs(session, world.lead_scope(session)).result(
            run_id, store=store
        )["provenance"]
    prompt = provenance["material_classification"]["prompt"]
    assert (prompt["origin"], prompt["data_class"], prompt["material_sha256"]) == (
        "baseline",
        "CLASS_C_INTERNAL",
        None,
    )
    assert (prompt["source"], prompt["declared_class"], prompt["declared_by"]) == (
        "code",
        None,
        None,
    )
