"""workflow engine: runs, steps, attempts, reservations, gates

Revision ID: e0e14f1b5e3c
Revises: 6750a204efd9
Created: 2026-09-22 09:15:52.581769+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e0e14f1b5e3c'
down_revision: str | None = '6750a204efd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_reservations',
    sa.Column('reservation_id', sa.String(length=64), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('attempt_id', sa.String(length=64), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('settled_amount_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('RESERVED','SETTLED','RELEASED','SETTLED_UNCERTAIN')", name=op.f('ck_budget_reservations_reservation_status_known')),
    sa.CheckConstraint('amount_usd >= 0', name=op.f('ck_budget_reservations_reservation_amount_non_negative')),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], name=op.f('fk_budget_reservations_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id', name=op.f('pk_budget_reservations'))
    )
    op.create_index('ix_reservations_attempt', 'budget_reservations', ['attempt_id'], unique=False)
    op.create_index('ix_reservations_study_status', 'budget_reservations', ['study_id', 'status'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('project_revision', sa.Integer(), nullable=False),
    sa.Column('workflow_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('project_revision >= 1', name=op.f('ck_workflow_runs_run_revision_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_workflow_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], name=op.f('fk_workflow_runs_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_workflow_runs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_workflow_runs_idempotency_key'))
    )
    op.create_index('ix_runs_status', 'workflow_runs', ['status', 'priority'], unique=False)
    op.create_index('ix_runs_study', 'workflow_runs', ['study_id', 'created_at'], unique=False)
    op.create_table('step_runs',
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('stage_type', sa.String(length=64), nullable=False),
    sa.Column('artifact_target', sa.String(length=64), nullable=False),
    sa.Column('interaction_mode', sa.String(length=32), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('attempts_recorded', sa.Integer(), nullable=False),
    sa.Column('attempts_consumed', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('waiting_reason', sa.String(length=128), nullable=True),
    sa.Column('runnable_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('input_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('output_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempts_consumed >= 0', name=op.f('ck_step_runs_step_attempts_consumed_non_negative')),
    sa.CheckConstraint('attempts_recorded >= 0', name=op.f('ck_step_runs_step_attempts_recorded_non_negative')),
    sa.CheckConstraint('max_attempts >= 1', name=op.f('ck_step_runs_step_max_attempts_positive')),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], name=op.f('fk_step_runs_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', name=op.f('pk_step_runs')),
    sa.UniqueConstraint('run_id', 'node_key', name='step_node_unique')
    )
    op.create_index('ix_steps_claimable', 'step_runs', ['status', 'runnable_after', 'priority'], unique=False)
    op.create_index('ix_steps_run', 'step_runs', ['run_id', 'ordinal'], unique=False)
    op.create_table('workflow_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('attempt_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], name=op.f('fk_workflow_events_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_workflow_events'))
    )
    op.create_index('ix_workflow_events_run', 'workflow_events', ['run_id', 'event_id'], unique=False)
    op.create_table('step_attempts',
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('paid_call_dispatched', sa.Boolean(), nullable=False),
    sa.Column('paid_call_outcome_known', sa.Boolean(), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('failure_class', sa.String(length=32), nullable=True),
    sa.Column('error_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('output_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('actual_cost_usd', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('actual_cost_usd >= 0', name=op.f('ck_step_attempts_attempt_actual_non_negative')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_step_attempts_attempt_number_positive')),
    sa.CheckConstraint('estimated_cost_usd >= 0', name=op.f('ck_step_attempts_attempt_estimate_non_negative')),
    sa.ForeignKeyConstraint(['step_id'], ['step_runs.step_id'], name=op.f('fk_step_attempts_step_id_step_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id', name=op.f('pk_step_attempts')),
    sa.UniqueConstraint('step_id', 'attempt_number', name='attempt_number_unique')
    )
    op.create_index('ix_attempts_lease', 'step_attempts', ['status', 'lease_until'], unique=False)
    op.create_index('ix_attempts_step', 'step_attempts', ['step_id', 'attempt_number'], unique=False)
    op.create_table('step_dependencies',
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('depends_on_step_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_step_id'], ['step_runs.step_id'], name=op.f('fk_step_dependencies_depends_on_step_id_step_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['step_runs.step_id'], name=op.f('fk_step_dependencies_step_id_step_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', 'depends_on_step_id', name=op.f('pk_step_dependencies'))
    )
    op.create_index('ix_step_deps_reverse', 'step_dependencies', ['depends_on_step_id'], unique=False)
    op.create_table('workflow_gates',
    sa.Column('gate_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('gate_type', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('context_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('decision_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('produced_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('decided_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('PENDING','DECIDED','CANCELLED','EXPIRED')", name=op.f('ck_workflow_gates_gate_status_known')),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], name=op.f('fk_workflow_gates_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['step_runs.step_id'], name=op.f('fk_workflow_gates_step_id_step_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gate_id', name=op.f('pk_workflow_gates'))
    )
    op.create_index('ix_gates_pending', 'workflow_gates', ['run_id', 'status'], unique=False)
    op.add_column('access_audit', sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False))
    op.add_column('project_artifacts', sa.Column('produced_by_user_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_artifacts', 'produced_by_user_id')
    op.drop_column('access_audit', 'payload')
    op.drop_index('ix_gates_pending', table_name='workflow_gates')
    op.drop_table('workflow_gates')
    op.drop_index('ix_step_deps_reverse', table_name='step_dependencies')
    op.drop_table('step_dependencies')
    op.drop_index('ix_attempts_step', table_name='step_attempts')
    op.drop_index('ix_attempts_lease', table_name='step_attempts')
    op.drop_table('step_attempts')
    op.drop_index('ix_workflow_events_run', table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index('ix_steps_run', table_name='step_runs')
    op.drop_index('ix_steps_claimable', table_name='step_runs')
    op.drop_table('step_runs')
    op.drop_index('ix_runs_study', table_name='workflow_runs')
    op.drop_index('ix_runs_status', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index('ix_reservations_study_status', table_name='budget_reservations')
    op.drop_index('ix_reservations_attempt', table_name='budget_reservations')
    op.drop_table('budget_reservations')
    # ### end Alembic commands ###
