"""population companion sets

A dataset version is usable only with its complete companion set when its
contract declares one (``aia_core.domain.population.companions``):

1. ``population_companion_sets`` -- one validated set per version, insert-once,
   with the companion-set digest, the joint-certificate state it evaluated to and
   the full report it was accepted on.
2. ``population_companion_assets`` -- each companion's identity (sha256, bytes)
   and where its bytes live, so every load can re-verify them.

No backfill: versions registered before this revision have no set, which is the
correct state -- a contract that declares companions treats them as not yet
usable until a set is attached.

Revision ID: cadbca872dc5
Revises: 1068fd22455d
Created: 2026-09-22 22:11:08.086615+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cadbca872dc5'
down_revision: str | None = '1068fd22455d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population_companion_sets',
    sa.Column('version_id', sa.String(length=128), nullable=False),
    sa.Column('set_sha256', sa.String(length=64), nullable=False),
    sa.Column('joint_state', sa.String(length=32), nullable=False),
    sa.Column('report_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('attached_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attached_by', sa.String(length=64), nullable=False),
    sa.CheckConstraint("joint_state in ('CERTIFIED','NOT_THIS_PANEL','UNKNOWN_STATUS','UNPARSEABLE','MISSING')", name=op.f('ck_population_companion_sets_population_companion_joint_state_known')),
    sa.ForeignKeyConstraint(['version_id'], ['population_dataset_versions.version_id'], name=op.f('fk_population_companion_sets_version_id_population_dataset_versions')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_population_companion_sets'))
    )
    op.create_table('population_companion_assets',
    sa.Column('version_id', sa.String(length=128), nullable=False),
    sa.Column('asset_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.CheckConstraint('byte_size > 0', name=op.f('ck_population_companion_assets_population_companion_bytes_positive')),
    sa.ForeignKeyConstraint(['version_id'], ['population_companion_sets.version_id'], name=op.f('fk_population_companion_assets_version_id_population_companion_sets')),
    sa.PrimaryKeyConstraint('version_id', 'asset_id', name=op.f('pk_population_companion_assets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population_companion_assets')
    op.drop_table('population_companion_sets')
    # ### end Alembic commands ###
