"""scope: organizations, clients, studies, grants

Revision ID: 6750a204efd9
Revises: f10611d239a4
Created: 2026-09-21 13:39:42.794181+00:00
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "6750a204efd9"
down_revision: str | None = "f10611d239a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_audit",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=True),
        sa.Column("study_id", sa.String(length=64), nullable=True),
        sa.Column("subject_user_id", sa.String(length=64), nullable=True),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_access_audit")),
    )
    op.create_index(
        "ix_access_audit_org",
        "access_audit",
        ["organization_id", "event_id"],
        unique=False,
    )
    op.create_table(
        "organizations",
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("organization_id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("external_subject", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_users_external_subject")),
    )
    op.create_index("ix_users_subject", "users", ["external_subject"], unique=False)
    op.create_table(
        "clients",
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reference", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status in ('ACTIVE','DORMANT','ARCHIVED')",
            name=op.f("ck_clients_client_status_known"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.organization_id"],
            name=op.f("fk_clients_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("client_id", name=op.f("pk_clients")),
        sa.UniqueConstraint("organization_id", "slug", name="client_slug_unique"),
    )
    op.create_index(
        "ix_clients_org", "clients", ["organization_id", "status"], unique=False
    )
    op.create_table(
        "organization_members",
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role in ('OWNER','ADMIN','MEMBER')",
            name=op.f("ck_organization_members_org_role_known"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.organization_id"],
            name=op.f("fk_organization_members_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_organization_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "user_id", name=op.f("pk_organization_members")
        ),
    )
    op.create_index(
        "ix_org_members_user", "organization_members", ["user_id"], unique=False
    )
    op.create_table(
        "client_grants",
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("granted_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role in ('VIEWER','REVIEWER','RESEARCHER','LEAD')",
            name=op.f("ck_client_grants_client_grant_role_known"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("fk_client_grants_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_client_grants_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("client_id", "user_id", name=op.f("pk_client_grants")),
    )
    op.create_index("ix_client_grants_user", "client_grants", ["user_id"], unique=False)
    op.create_table(
        "studies",
        sa.Column("study_id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("budget_usd", sa.Float(), nullable=False),
        sa.Column("spent_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status in ('DRAFT','ACTIVE','IN_REVIEW','DELIVERED','ARCHIVED','CANCELLED')",
            name=op.f("ck_studies_study_status_known"),
        ),
        sa.CheckConstraint(
            "budget_usd >= 0", name=op.f("ck_studies_study_budget_non_negative")
        ),
        sa.CheckConstraint(
            "spent_usd >= 0", name=op.f("ck_studies_study_spent_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("fk_studies_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.organization_id"],
            name=op.f("fk_studies_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("study_id", name=op.f("pk_studies")),
        sa.UniqueConstraint("client_id", "slug", name="study_slug_unique"),
    )
    op.create_index(
        "ix_studies_client", "studies", ["client_id", "status"], unique=False
    )
    op.create_index(
        "ix_studies_org_modified",
        "studies",
        ["organization_id", "modified_at"],
        unique=False,
    )
    op.create_table(
        "study_grants",
        sa.Column("study_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("granted_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role in ('VIEWER','REVIEWER','RESEARCHER','LEAD')",
            name=op.f("ck_study_grants_study_grant_role_known"),
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.study_id"],
            name=op.f("fk_study_grants_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_study_grants_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("study_id", "user_id", name=op.f("pk_study_grants")),
    )
    op.create_index("ix_study_grants_user", "study_grants", ["user_id"], unique=False)
    op.add_column(
        "projects", sa.Column("client_id", sa.String(length=64), nullable=False)
    )
    op.add_column(
        "projects", sa.Column("study_id", sa.String(length=64), nullable=False)
    )
    op.drop_index(op.f("ix_projects_org_modified"), table_name="projects")
    op.create_index(
        "ix_projects_client_modified",
        "projects",
        ["client_id", "modified_at"],
        unique=False,
    )
    op.create_index(
        "ix_projects_study_modified",
        "projects",
        ["study_id", "modified_at"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_projects_study_id_studies"),
        "projects",
        "studies",
        ["study_id"],
        ["study_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_projects_client_id_clients"),
        "projects",
        "clients",
        ["client_id"],
        ["client_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_projects_client_id_clients"), "projects", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_projects_study_id_studies"), "projects", type_="foreignkey"
    )
    op.drop_index("ix_projects_study_modified", table_name="projects")
    op.drop_index("ix_projects_client_modified", table_name="projects")
    op.create_index(
        op.f("ix_projects_org_modified"),
        "projects",
        ["organization_id", "modified_at"],
        unique=False,
    )
    op.drop_column("projects", "study_id")
    op.drop_column("projects", "client_id")
    op.drop_index("ix_study_grants_user", table_name="study_grants")
    op.drop_table("study_grants")
    op.drop_index("ix_studies_org_modified", table_name="studies")
    op.drop_index("ix_studies_client", table_name="studies")
    op.drop_table("studies")
    op.drop_index("ix_client_grants_user", table_name="client_grants")
    op.drop_table("client_grants")
    op.drop_index("ix_org_members_user", table_name="organization_members")
    op.drop_table("organization_members")
    op.drop_index("ix_clients_org", table_name="clients")
    op.drop_table("clients")
    op.drop_index("ix_users_subject", table_name="users")
    op.drop_table("users")
    op.drop_table("organizations")
    op.drop_index("ix_access_audit_org", table_name="access_audit")
    op.drop_table("access_audit")
    # ### end Alembic commands ###
