"""initial project graph

Revision ID: f10611d239a4
Revises:
Created: 2026-09-21 12:55:50.182378+00:00
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f10611d239a4"
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("project_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_revision", sa.Integer(), nullable=False),
        sa.Column("current_stage", sa.String(length=64), nullable=False),
        sa.Column("last_completed_stage", sa.String(length=64), nullable=True),
        sa.Column("parent_project_id", sa.String(length=64), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("preferred_provider", sa.String(length=64), nullable=False),
        sa.Column("provider_policy", sa.String(length=32), nullable=False),
        sa.Column("max_api_cost_usd", sa.Float(), nullable=False),
        sa.Column("runtime_version", sa.String(length=64), nullable=False),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("trashed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "project_type in ('research','simulation')",
            name=op.f("ck_projects_project_type_known"),
        ),
        sa.CheckConstraint(
            "current_revision >= 0",
            name=op.f("ck_projects_current_revision_non_negative"),
        ),
        sa.CheckConstraint(
            "max_api_cost_usd >= 0", name=op.f("ck_projects_budget_non_negative")
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_projects")),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(
            "ix_projects_org_modified", ["organization_id", "modified_at"], unique=False
        )
        batch_op.create_index(
            "ix_projects_org_status", ["organization_id", "status"], unique=False
        )

    op.create_table(
        "project_artifacts",
        sa.Column("artifact_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("stage_type", sa.String(length=64), nullable=False),
        sa.Column("artifact_type", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("runtime_version", sa.String(length=64), nullable=False),
        sa.Column("produced_by_job_id", sa.String(length=64), nullable=True),
        sa.Column(
            "artifact_metadata",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("is_frozen", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_project_artifacts_size_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
            name=op.f("fk_project_artifacts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("artifact_id", name=op.f("pk_project_artifacts")),
    )
    with op.batch_alter_table("project_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_artifacts_reuse",
            ["project_id", "stage_type", "artifact_type", "input_fingerprint"],
            unique=False,
        )
        batch_op.create_index(
            "ix_artifacts_revision",
            ["project_id", "revision", "stage_type"],
            unique=False,
        )

    op.create_table(
        "project_events",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=True),
        sa.Column("stage_type", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
            name=op.f("fk_project_events_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_project_events")),
    )
    with op.batch_alter_table("project_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_events_project", ["project_id", "event_id"], unique=False
        )

    op.create_table(
        "project_provider_events",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=True),
        sa.Column("stage_type", sa.String(length=64), nullable=True),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("from_provider", sa.String(length=64), nullable=True),
        sa.Column("to_provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("explicit_user_action", sa.Boolean(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("actual_cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
            name=op.f("fk_project_provider_events_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_project_provider_events")),
        sa.UniqueConstraint("project_id", "event_id", name="provider_event_unique"),
    )
    with op.batch_alter_table("project_provider_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_provider_events_project", ["project_id", "created_at"], unique=False
        )

    op.create_table(
        "project_revisions",
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.String(length=64), nullable=False),
        sa.Column("parent_revision", sa.Integer(), nullable=True),
        sa.Column("branch_id", sa.String(length=64), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "content",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "analysis",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "changed_fields",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "impact",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("questionnaire_version", sa.String(length=32), nullable=False),
        sa.Column("panel_version", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "revision >= 1", name=op.f("ck_project_revisions_revision_starts_at_one")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
            name=op.f("fk_project_revisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "revision", name=op.f("pk_project_revisions")
        ),
        sa.UniqueConstraint(
            "revision_id", name=op.f("uq_project_revisions_revision_id")
        ),
    )
    with op.batch_alter_table("project_revisions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_revisions_sha", ["project_id", "content_sha256"], unique=False
        )

    op.create_table(
        "project_artifact_dependencies",
        sa.Column("artifact_id", sa.String(length=64), nullable=False),
        sa.Column("depends_on_artifact_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["project_artifacts.artifact_id"],
            name=op.f("fk_project_artifact_dependencies_artifact_id_project_artifacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "artifact_id",
            "depends_on_artifact_id",
            name=op.f("pk_project_artifact_dependencies"),
        ),
    )
    op.create_table(
        "project_stages",
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("stage_type", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("current_job_id", sa.String(length=64), nullable=True),
        sa.Column("last_checkpoint", sa.Text(), nullable=True),
        sa.Column("waiting_reason", sa.String(length=128), nullable=True),
        sa.Column("quota_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "artifact_ids",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "revision"],
            ["project_revisions.project_id", "project_revisions.revision"],
            name=op.f("fk_project_stages_project_id_project_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "revision", "stage_type", name=op.f("pk_project_stages")
        ),
    )
    with op.batch_alter_table("project_stages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_stages_lookup",
            ["project_id", "revision", "ordinal"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_stages", schema=None) as batch_op:
        batch_op.drop_index("ix_project_stages_lookup")

    op.drop_table("project_stages")
    op.drop_table("project_artifact_dependencies")
    with op.batch_alter_table("project_revisions", schema=None) as batch_op:
        batch_op.drop_index("ix_project_revisions_sha")

    op.drop_table("project_revisions")
    with op.batch_alter_table("project_provider_events", schema=None) as batch_op:
        batch_op.drop_index("ix_provider_events_project")

    op.drop_table("project_provider_events")
    with op.batch_alter_table("project_events", schema=None) as batch_op:
        batch_op.drop_index("ix_project_events_project")

    op.drop_table("project_events")
    with op.batch_alter_table("project_artifacts", schema=None) as batch_op:
        batch_op.drop_index("ix_artifacts_revision")
        batch_op.drop_index("ix_artifacts_reuse")

    op.drop_table("project_artifacts")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("ix_projects_org_status")
        batch_op.drop_index("ix_projects_org_modified")

    op.drop_table("projects")
    # ### end Alembic commands ###
