"""population registry and run bindings

Four tables for the ``population`` bounded context
(``aia_core.domain.population``):

1. ``population_dataset_versions`` -- content-addressed, insert-only dataset
   versions. ``content_sha256`` is unique, ``(dataset_id, label)`` is unique, and
   ``parent_version_id`` records lineage without cascading.
2. ``populations`` -- the STATIC and LIVE populations of a dataset (one of each)
   and the version each currently resolves to. The single authority for "which
   population is in use".
3. ``population_promotions`` -- append-only history of every establish and
   promote; SUPERSEDED is derived from it, never stored.
4. ``run_population_bindings`` -- the resolved population a workflow run is
   computed over, one row per run, cascading with the run and never updated.

Platform reference data carries no organization/client/study; the run binding
inherits its scope from ``workflow_runs``. No data migration: nothing existed to
backfill, and a run created before this revision has no binding, which the
application reads as "this run reads no population".

Revision ID: 1068fd22455d
Revises: 4599186ff65b
Created: 2026-09-22 21:21:48.848842+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1068fd22455d'
down_revision: str | None = '4599186ff65b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population_dataset_versions',
    sa.Column('version_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(length=128), nullable=False),
    sa.Column('dictionary_sha256', sa.String(length=64), nullable=False),
    sa.Column('field_names_sha256', sa.String(length=64), nullable=False),
    sa.Column('parent_version_id', sa.String(length=128), nullable=True),
    sa.Column('storage_location', sa.Text(), nullable=False),
    sa.Column('dictionary_location', sa.Text(), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('validation_json', sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_by', sa.String(length=64), nullable=False),
    sa.CheckConstraint('byte_size > 0', name=op.f('ck_population_dataset_versions_population_version_bytes_positive')),
    sa.CheckConstraint('column_count > 0', name=op.f('ck_population_dataset_versions_population_version_columns_positive')),
    sa.CheckConstraint('parent_version_id IS NULL OR parent_version_id <> version_id', name=op.f('ck_population_dataset_versions_population_version_not_own_parent')),
    sa.CheckConstraint('row_count > 0', name=op.f('ck_population_dataset_versions_population_version_rows_positive')),
    sa.ForeignKeyConstraint(['parent_version_id'], ['population_dataset_versions.version_id'], name=op.f('fk_population_dataset_versions_parent_version_id_population_dataset_versions')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_population_dataset_versions')),
    sa.UniqueConstraint('content_sha256', name=op.f('uq_population_dataset_versions_content_sha256')),
    sa.UniqueConstraint('dataset_id', 'label', name='population_version_label')
    )
    op.create_index('ix_population_versions_dataset', 'population_dataset_versions', ['dataset_id', 'imported_at'], unique=False)
    op.create_table('populations',
    sa.Column('population_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('current_version_id', sa.String(length=128), nullable=False),
    sa.Column('established_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('established_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind in ('STATIC','LIVE')", name=op.f('ck_populations_population_kind_known')),
    sa.ForeignKeyConstraint(['current_version_id'], ['population_dataset_versions.version_id'], name=op.f('fk_populations_current_version_id_population_dataset_versions')),
    sa.PrimaryKeyConstraint('population_id', name=op.f('pk_populations')),
    sa.UniqueConstraint('dataset_id', 'kind', name='population_one_per_kind')
    )
    op.create_table('population_promotions',
    sa.Column('promotion_id', sa.String(length=64), nullable=False),
    sa.Column('population_id', sa.String(length=64), nullable=False),
    sa.Column('from_version_id', sa.String(length=128), nullable=True),
    sa.Column('to_version_id', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.population_id'], name=op.f('fk_population_promotions_population_id_populations')),
    sa.ForeignKeyConstraint(['to_version_id'], ['population_dataset_versions.version_id'], name=op.f('fk_population_promotions_to_version_id_population_dataset_versions')),
    sa.PrimaryKeyConstraint('promotion_id', name=op.f('pk_population_promotions'))
    )
    op.create_index('ix_population_promotions_population', 'population_promotions', ['population_id', 'promoted_at'], unique=False)
    op.create_table('run_population_bindings',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=128), nullable=False),
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('contract_id', sa.String(length=128), nullable=False),
    sa.Column('population_id', sa.String(length=64), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=False),
    sa.Column('weight_role', sa.String(length=64), nullable=False),
    sa.Column('weight_column', sa.String(length=128), nullable=False),
    sa.Column('view', sa.String(length=16), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("resolution in ('LIVE_CURRENT','STATIC_REFERENCE','PINNED')", name=op.f('ck_run_population_bindings_run_population_resolution_known')),
    sa.CheckConstraint("view in ('BASE','ANALYSIS')", name=op.f('ck_run_population_bindings_run_population_view_known')),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], name=op.f('fk_run_population_bindings_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['population_dataset_versions.version_id'], name=op.f('fk_run_population_bindings_version_id_population_dataset_versions')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_run_population_bindings'))
    )
    op.create_index('ix_run_population_version', 'run_population_bindings', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_population_version', table_name='run_population_bindings')
    op.drop_table('run_population_bindings')
    op.drop_index('ix_population_promotions_population', table_name='population_promotions')
    op.drop_table('population_promotions')
    op.drop_table('populations')
    op.drop_index('ix_population_versions_dataset', table_name='population_dataset_versions')
    op.drop_table('population_dataset_versions')
    # ### end Alembic commands ###
