"""ai usage ledger

`ai_usage_events` is the append-only ledger of every model call: a DISPATCHED
row written before the call leaves, a terminal row after, and a COMPENSATION row
when an uncertain call is resolved. `(call_id, outcome)` is unique so no entry
can be counted twice, and only a compensating row may carry a negative cost.

The study foreign key deliberately does not cascade: a study with ledger entries
cannot be deleted out from under its accounting record.

Revision ID: 1cd2a5acd29f
Revises: 4599186ff65b
Created: 2026-09-22 21:34:06.455315+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '1cd2a5acd29f'
down_revision: str | None = '4599186ff65b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('attempt_id', sa.String(length=64), nullable=True),
    sa.Column('reservation_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_id', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('runtime_version', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('served_model', sa.String(length=128), nullable=False),
    sa.Column('route_id', sa.String(length=128), nullable=False),
    sa.Column('data_class', sa.String(length=64), nullable=False),
    sa.Column('residency_zone', sa.String(length=16), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('error_kind', sa.String(length=32), nullable=True),
    sa.Column('failure_class', sa.String(length=32), nullable=True),
    sa.Column('finish_reason', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_write_input_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.String(length=32), nullable=False),
    sa.Column('ceiling_usd', sa.Float(), nullable=False),
    sa.Column('schema_fingerprint', sa.String(length=80), nullable=True),
    sa.Column('substituted_from', sa.String(length=128), nullable=True),
    sa.Column('fallback_from', sa.String(length=255), nullable=True),
    sa.Column('fallback_authorised_by', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('supersedes_event_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("cost_basis in ('SUBSCRIPTION','METERED','CEILING','COMPENSATION')", name=op.f('ck_ai_usage_events_usage_cost_basis_known')),
    sa.CheckConstraint("cost_usd >= 0 OR cost_basis = 'COMPENSATION'", name=op.f('ck_ai_usage_events_usage_cost_non_negative')),
    sa.CheckConstraint("outcome in ('DISPATCHED','SUCCEEDED','FAILED','UNCERTAIN','RESOLVED_BILLED','RESOLVED_NOT_BILLED')", name=op.f('ck_ai_usage_events_usage_outcome_known')),
    sa.CheckConstraint('ceiling_usd >= 0', name=op.f('ck_ai_usage_events_usage_ceiling_non_negative')),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], name=op.f('fk_ai_usage_events_study_id_studies')),
    sa.ForeignKeyConstraint(['supersedes_event_id'], ['ai_usage_events.event_id'], name=op.f('fk_ai_usage_events_supersedes_event_id_ai_usage_events')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_ai_usage_events')),
    sa.UniqueConstraint('call_id', 'outcome', name='usage_call_outcome_unique')
    )
    op.create_index('ix_usage_attempt', 'ai_usage_events', ['attempt_id'], unique=False)
    op.create_index('ix_usage_call', 'ai_usage_events', ['call_id'], unique=False)
    op.create_index('ix_usage_provider_request', 'ai_usage_events', ['provider_request_id'], unique=False)
    op.create_index('ix_usage_study_time', 'ai_usage_events', ['study_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_study_time', table_name='ai_usage_events')
    op.drop_index('ix_usage_provider_request', table_name='ai_usage_events')
    op.drop_index('ix_usage_call', table_name='ai_usage_events')
    op.drop_index('ix_usage_attempt', table_name='ai_usage_events')
    op.drop_table('ai_usage_events')
    # ### end Alembic commands ###
