"""GENERATED by apps/web/scripts/build-tokens.mjs from apps/web/src/design/tokens.json.

Do not edit by hand: `npm run tokens:check` fails CI on drift. The print register of
the design system for the DOCX report — the light theme's colours (a report is
paper even when the Studio is dark), the Deliverable type group in points, and the
page geometry. Pure constants: importable with nothing installed but the stdlib.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True)
class PrintStyle:
    """One Deliverable type style, resolved to a Word font and point metrics."""

    name: str
    font: str
    family: str
    bold: bool
    italic: bool
    size_pt: float
    leading_pt: float
    before_pt: float
    after_pt: float
    caps: bool
    tracking_pt: float


@dataclass(frozen=True)
class PageGeometry:
    """A4 portrait, in millimetres. Inside/outside margins mirror on facing pages."""

    width_mm: float
    height_mm: float
    margin_top_mm: float
    margin_bottom_mm: float
    margin_inside_mm: float
    margin_outside_mm: float
    header_mm: float
    footer_mm: float


PAGE: Final = PageGeometry(
    width_mm=210.0,
    height_mm=297.0,
    margin_top_mm=25.0,
    margin_bottom_mm=22.0,
    margin_inside_mm=24.0,
    margin_outside_mm=20.0,
    header_mm=11.0,
    footer_mm=10.0,
)

#: Resolved light-theme colours, `#rrggbb`.
COLORS: Final[dict[str, str]] = {
    "doc-paper": "#fffdfa",
    "doc-ink": "#0f1216",
    "doc-muted": "#44484e",
    "doc-rule": "#c6c4be",
    "doc-accent": "#0d5279",
    "doc-wash": "#f3f1ec",
    "evidence-mark": "#151a20",
    "evidence-hatch": "#5c6167",
    "viz-cat-1": "#2a78d6",
    "viz-cat-2": "#eb6834",
    "viz-cat-3": "#1baf7a",
    "viz-cat-4": "#4a3aa7",
    "viz-cat-5": "#008300",
    "viz-cat-6": "#e87ba4",
    "viz-seq-1": "#cde2fb",
    "viz-seq-2": "#9ec5f4",
    "viz-seq-3": "#6da7ec",
    "viz-seq-4": "#3987e5",
    "viz-seq-5": "#256abf",
    "viz-seq-6": "#184f95",
    "viz-seq-7": "#0d366b",
    "viz-div-1": "#184f95",
    "viz-div-2": "#3987e5",
    "viz-div-3": "#9ec5f4",
    "viz-div-4": "#f0efec",
    "viz-div-5": "#feaa89",
    "viz-div-6": "#cf6335",
    "viz-div-7": "#883001",
    "viz-grid": "#e1dfdb",
    "viz-axis": "#43484f",
}

#: The Deliverable type group, by style name.
STYLES: Final[dict[str, PrintStyle]] = {
    "doc-title": PrintStyle(
        name="doc-title",
        font="Source Serif 4 Display Semibold",
        family="display",
        bold=False,
        italic=False,
        size_pt=30.0,
        leading_pt=34.0,
        before_pt=0.0,
        after_pt=10.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-h1": PrintStyle(
        name="doc-h1",
        font="Source Serif 4 Semibold",
        family="serif",
        bold=False,
        italic=False,
        size_pt=18.0,
        leading_pt=23.0,
        before_pt=0.0,
        after_pt=10.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-h2": PrintStyle(
        name="doc-h2",
        font="Source Serif 4 Semibold",
        family="serif",
        bold=False,
        italic=False,
        size_pt=13.5,
        leading_pt=18.0,
        before_pt=16.0,
        after_pt=6.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-lede": PrintStyle(
        name="doc-lede",
        font="Source Serif 4",
        family="serif",
        bold=False,
        italic=False,
        size_pt=12.5,
        leading_pt=18.0,
        before_pt=4.0,
        after_pt=10.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-body": PrintStyle(
        name="doc-body",
        font="Source Serif 4",
        family="serif",
        bold=False,
        italic=False,
        size_pt=10.5,
        leading_pt=16.8,
        before_pt=0.0,
        after_pt=7.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-caption": PrintStyle(
        name="doc-caption",
        font="IBM Plex Sans",
        family="sans",
        bold=False,
        italic=False,
        size_pt=8.5,
        leading_pt=12.0,
        before_pt=4.0,
        after_pt=10.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-footnote": PrintStyle(
        name="doc-footnote",
        font="Source Serif 4",
        family="serif",
        bold=False,
        italic=False,
        size_pt=8.5,
        leading_pt=11.5,
        before_pt=0.0,
        after_pt=2.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-subtitle": PrintStyle(
        name="doc-subtitle",
        font="Source Serif 4",
        family="serif",
        bold=False,
        italic=False,
        size_pt=14.5,
        leading_pt=19.0,
        before_pt=0.0,
        after_pt=18.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-kicker": PrintStyle(
        name="doc-kicker",
        font="IBM Plex Sans SmBld",
        family="sans",
        bold=False,
        italic=False,
        size_pt=8.0,
        leading_pt=11.0,
        before_pt=0.0,
        after_pt=6.0,
        caps=True,
        tracking_pt=0.6,
    ),
    "doc-h3": PrintStyle(
        name="doc-h3",
        font="Source Serif 4 Semibold",
        family="serif",
        bold=False,
        italic=False,
        size_pt=11.5,
        leading_pt=15.5,
        before_pt=12.0,
        after_pt=4.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-meta": PrintStyle(
        name="doc-meta",
        font="IBM Plex Sans",
        family="sans",
        bold=False,
        italic=False,
        size_pt=9.0,
        leading_pt=13.0,
        before_pt=0.0,
        after_pt=3.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-running": PrintStyle(
        name="doc-running",
        font="IBM Plex Sans",
        family="sans",
        bold=False,
        italic=False,
        size_pt=7.5,
        leading_pt=10.0,
        before_pt=0.0,
        after_pt=0.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-table": PrintStyle(
        name="doc-table",
        font="IBM Plex Sans",
        family="sans",
        bold=False,
        italic=False,
        size_pt=8.5,
        leading_pt=11.5,
        before_pt=1.5,
        after_pt=1.5,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-table-head": PrintStyle(
        name="doc-table-head",
        font="IBM Plex Sans SmBld",
        family="sans",
        bold=False,
        italic=False,
        size_pt=8.0,
        leading_pt=11.0,
        before_pt=2.0,
        after_pt=2.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-kpi": PrintStyle(
        name="doc-kpi",
        font="IBM Plex Sans SmBld",
        family="sans",
        bold=False,
        italic=False,
        size_pt=20.0,
        leading_pt=24.0,
        before_pt=0.0,
        after_pt=2.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-quote": PrintStyle(
        name="doc-quote",
        font="Source Serif 4",
        family="serif",
        bold=False,
        italic=True,
        size_pt=11.0,
        leading_pt=16.5,
        before_pt=4.0,
        after_pt=8.0,
        caps=False,
        tracking_pt=0.0,
    ),
    "doc-mono": PrintStyle(
        name="doc-mono",
        font="IBM Plex Mono",
        family="mono",
        bold=False,
        italic=False,
        size_pt=7.5,
        leading_pt=10.5,
        before_pt=0.0,
        after_pt=0.0,
        caps=False,
        tracking_pt=0.0,
    ),
}

#: Every Word font name a report may use; each must be embeddable.
FONTS: Final[tuple[str, ...]] = (
    "Source Serif 4",
    "Source Serif 4 Semibold",
    "Source Serif 4 Display Semibold",
    "IBM Plex Sans",
    "IBM Plex Sans SmBld",
    "IBM Plex Mono",
)
