// GENERATED by scripts/build-tokens.mjs from src/design/tokens.json — do not edit by hand.

/** Resolved colour values per theme, for JavaScript consumers (charts, canvas). CSS uses the custom properties. */
export const colors = {
  "surface": {
    "light": "#f9f6f2",
    "dark": "#0f1215"
  },
  "surface-raised": {
    "light": "#fefcf9",
    "dark": "#171a1e"
  },
  "surface-sunken": {
    "light": "#f1eee9",
    "dark": "#090b0f"
  },
  "surface-overlay": {
    "light": "#fefdfb",
    "dark": "#1d2125"
  },
  "border": {
    "light": "#dad7d2",
    "dark": "#2f3338"
  },
  "border-strong": {
    "light": "#7b8187",
    "dark": "#70757c"
  },
  "ink": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "ink-muted": {
    "light": "#43484f",
    "dark": "#bdbab5"
  },
  "ink-faint": {
    "light": "#5c6167",
    "dark": "#9e9b96"
  },
  "surface-inverse": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "ink-inverse": {
    "light": "#f9f6f2",
    "dark": "#0f1215"
  },
  "signal": {
    "light": "#006b9f",
    "dark": "#6ac5e8"
  },
  "signal-wash": {
    "light": "#d7edfb",
    "dark": "#123144"
  },
  "signal-hover": {
    "light": "#005a86",
    "dark": "#8fd3ee"
  },
  "signal-wash-strong": {
    "light": "#cde8f8",
    "dark": "#183d55"
  },
  "signal-tint": {
    "light": "#eef6fb",
    "dark": "#152530"
  },
  "signal-edge": {
    "light": "#9ccbe8",
    "dark": "#2e5f7c"
  },
  "on-signal": {
    "light": "#fefcf9",
    "dark": "#090b0f"
  },
  "focus-ring": {
    "light": "#006b9f",
    "dark": "#6ac5e8"
  },
  "status-running": {
    "light": "#006b9f",
    "dark": "#6ac5e8"
  },
  "status-running-wash": {
    "light": "#d7edfb",
    "dark": "#132e3f"
  },
  "status-you": {
    "light": "#f5ae39",
    "dark": "#f7b746"
  },
  "on-status-you": {
    "light": "#151a20",
    "dark": "#0f1215"
  },
  "status-you-ink": {
    "light": "#97570d",
    "dark": "#f4bd62"
  },
  "status-you-wash": {
    "light": "#feeed3",
    "dark": "#3c2a0e"
  },
  "status-world": {
    "light": "#576574",
    "dark": "#97a7b7"
  },
  "status-world-wash": {
    "light": "#e3e8ee",
    "dark": "#21272d"
  },
  "status-fault": {
    "light": "#b52524",
    "dark": "#f47b74"
  },
  "on-status-fault": {
    "light": "#fefcf9",
    "dark": "#090b0f"
  },
  "status-fault-wash": {
    "light": "#ffe8e6",
    "dark": "#431f1d"
  },
  "status-recovery": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "on-status-recovery": {
    "light": "#f9f6f2",
    "dark": "#0f1215"
  },
  "status-recovery-hatch": {
    "light": "#e24942",
    "dark": "#da534f"
  },
  "status-done": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "status-inert": {
    "light": "#5c6167",
    "dark": "#9e9b96"
  },
  "viz-cat-1": {
    "light": "#2a78d6",
    "dark": "#3987e5"
  },
  "viz-cat-2": {
    "light": "#eb6834",
    "dark": "#d95926"
  },
  "viz-cat-3": {
    "light": "#1baf7a",
    "dark": "#199e70"
  },
  "viz-cat-4": {
    "light": "#4a3aa7",
    "dark": "#9085e9"
  },
  "viz-cat-5": {
    "light": "#008300",
    "dark": "#008300"
  },
  "viz-cat-6": {
    "light": "#e87ba4",
    "dark": "#d55181"
  },
  "viz-seq-1": {
    "light": "#cde2fb",
    "dark": "#0d366b"
  },
  "viz-seq-2": {
    "light": "#9ec5f4",
    "dark": "#184f95"
  },
  "viz-seq-3": {
    "light": "#6da7ec",
    "dark": "#256abf"
  },
  "viz-seq-4": {
    "light": "#3987e5",
    "dark": "#3987e5"
  },
  "viz-seq-5": {
    "light": "#256abf",
    "dark": "#6da7ec"
  },
  "viz-seq-6": {
    "light": "#184f95",
    "dark": "#9ec5f4"
  },
  "viz-seq-7": {
    "light": "#0d366b",
    "dark": "#cde2fb"
  },
  "viz-div-1": {
    "light": "#184f95",
    "dark": "#6da7ec"
  },
  "viz-div-2": {
    "light": "#3987e5",
    "dark": "#3987e5"
  },
  "viz-div-3": {
    "light": "#9ec5f4",
    "dark": "#184f95"
  },
  "viz-div-4": {
    "light": "#f0efec",
    "dark": "#383835"
  },
  "viz-div-5": {
    "light": "#feaa89",
    "dark": "#883001"
  },
  "viz-div-6": {
    "light": "#cf6335",
    "dark": "#cf6335"
  },
  "viz-div-7": {
    "light": "#883001",
    "dark": "#f08053"
  },
  "viz-grid": {
    "light": "#e1dfdb",
    "dark": "#272a2f"
  },
  "viz-axis": {
    "light": "#43484f",
    "dark": "#bdbab5"
  },
  "client-1": {
    "light": "#a0555c",
    "dark": "#efa8ac"
  },
  "client-2": {
    "light": "#6c2d0a",
    "dark": "#b87b60"
  },
  "client-3": {
    "light": "#2c5a21",
    "dark": "#7ca573"
  },
  "client-4": {
    "light": "#09816b",
    "dark": "#80d0bb"
  },
  "client-5": {
    "light": "#5e69a8",
    "dark": "#adbaf5"
  },
  "client-6": {
    "light": "#46376d",
    "dark": "#8f83b6"
  },
  "on-client": {
    "light": "#fefcf9",
    "dark": "#090b0f"
  },
  "doc-paper": {
    "light": "#fffdfa",
    "dark": "#fffdfa"
  },
  "doc-ink": {
    "light": "#0f1216",
    "dark": "#0f1216"
  },
  "doc-muted": {
    "light": "#44484e",
    "dark": "#44484e"
  },
  "doc-rule": {
    "light": "#c6c4be",
    "dark": "#c6c4be"
  },
  "doc-accent": {
    "light": "#0d5279",
    "dark": "#0d5279"
  },
  "evidence-mark": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "evidence-hatch": {
    "light": "#5c6167",
    "dark": "#9e9b96"
  },
  "null-mark": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "suppressed-fill": {
    "light": "#43484f",
    "dark": "#bdbab5"
  },
  "budget-spent": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "budget-reserved": {
    "light": "#006b9f",
    "dark": "#6ac5e8"
  },
  "budget-uncertain": {
    "light": "#b52524",
    "dark": "#f47b74"
  },
  "scope-above": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "selection": {
    "light": "#d7edfb",
    "dark": "#123144"
  }
} as const;

export type ColorToken = keyof typeof colors;
export type Theme = "light" | "dark";

/** The CSS custom property for a colour token, e.g. cssVar("ink") → "var(--ink)". */
export function cssVar(name: ColorToken): string {
  return `var(--${name})`;
}

export const scalars = {
  "space-half": "2px",
  "space-1": "4px",
  "space-2": "8px",
  "space-3": "12px",
  "space-4": "16px",
  "space-6": "24px",
  "space-8": "32px",
  "space-12": "48px",
  "radius-0": "0px",
  "radius-sm": "2px",
  "radius-md": "4px",
  "stroke-hairline": "1px",
  "stroke-mark": "1.5px",
  "stroke-emphasis": "2px",
  "stroke-scope": "4px",
  "row-compact": "28px",
  "row-comfortable": "36px",
  "control-compact": "24px",
  "control-comfortable": "32px",
  "duration-instant": "0ms",
  "duration-confirm": "120ms",
  "duration-panel": "180ms",
  "z-scope": "30",
  "z-overlay": "40",
  "z-toast": "50"
} as const;
