// GENERATED by scripts/build-tokens.mjs from src/design/tokens.json — do not edit by hand.

/** Resolved colour values per theme, for JavaScript consumers (charts, canvas). CSS uses the custom properties. */
export const colors = {
  "surface": {
    "light": "#eef0f4",
    "dark": "#0d1015"
  },
  "surface-raised": {
    "light": "#ffffff",
    "dark": "#151a21"
  },
  "surface-sunken": {
    "light": "#e5e8ee",
    "dark": "#0a0c10"
  },
  "surface-overlay": {
    "light": "#ffffff",
    "dark": "#1b212a"
  },
  "border": {
    "light": "#dde1e8",
    "dark": "#252c36"
  },
  "border-strong": {
    "light": "#7d8490",
    "dark": "#6d7684"
  },
  "ink": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "ink-muted": {
    "light": "#43484f",
    "dark": "#bdbab5"
  },
  "ink-faint": {
    "light": "#5c6167",
    "dark": "#9e9b96"
  },
  "surface-inverse": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "ink-inverse": {
    "light": "#f9f6f2",
    "dark": "#0f1215"
  },
  "signal": {
    "light": "#3557e0",
    "dark": "#8aa2ff"
  },
  "signal-wash": {
    "light": "#e8edfd",
    "dark": "#1a2242"
  },
  "signal-hover": {
    "light": "#2843b8",
    "dark": "#a9bbff"
  },
  "signal-wash-strong": {
    "light": "#d8e2fb",
    "dark": "#222c55"
  },
  "signal-tint": {
    "light": "#f3f6fe",
    "dark": "#131a30"
  },
  "signal-edge": {
    "light": "#b9c7f6",
    "dark": "#35457d"
  },
  "on-signal": {
    "light": "#ffffff",
    "dark": "#0a0c10"
  },
  "focus-ring": {
    "light": "#3557e0",
    "dark": "#8aa2ff"
  },
  "ai": {
    "light": "#a3319a",
    "dark": "#e07ad6"
  },
  "ai-strong": {
    "light": "#862680",
    "dark": "#f09ae7"
  },
  "ai-wash": {
    "light": "#f7ecf6",
    "dark": "#31273a"
  },
  "ai-edge": {
    "light": "#d6a2d2",
    "dark": "#7a4a7c"
  },
  "ai-ink": {
    "light": "#8a2783",
    "dark": "#f0a6e8"
  },
  "on-ai": {
    "light": "#ffffff",
    "dark": "#1a0b18"
  },
  "status-running": {
    "light": "#3557e0",
    "dark": "#8aa2ff"
  },
  "status-running-wash": {
    "light": "#e8edfd",
    "dark": "#18203c"
  },
  "status-you": {
    "light": "#f5ae39",
    "dark": "#f7b746"
  },
  "on-status-you": {
    "light": "#151a20",
    "dark": "#0f1215"
  },
  "status-you-ink": {
    "light": "#97570d",
    "dark": "#f4bd62"
  },
  "status-you-wash": {
    "light": "#feeed3",
    "dark": "#3c2a0e"
  },
  "status-world": {
    "light": "#576574",
    "dark": "#97a7b7"
  },
  "status-world-wash": {
    "light": "#e3e8ee",
    "dark": "#21272d"
  },
  "status-fault": {
    "light": "#b52524",
    "dark": "#f47b74"
  },
  "on-status-fault": {
    "light": "#fefcf9",
    "dark": "#090b0f"
  },
  "status-fault-wash": {
    "light": "#ffe8e6",
    "dark": "#431f1d"
  },
  "status-recovery": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "on-status-recovery": {
    "light": "#f9f6f2",
    "dark": "#0f1215"
  },
  "status-recovery-hatch": {
    "light": "#e24942",
    "dark": "#da534f"
  },
  "status-done": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "status-inert": {
    "light": "#5c6167",
    "dark": "#9e9b96"
  },
  "viz-cat-1": {
    "light": "#2a78d6",
    "dark": "#3987e5"
  },
  "viz-cat-2": {
    "light": "#eb6834",
    "dark": "#d95926"
  },
  "viz-cat-3": {
    "light": "#1baf7a",
    "dark": "#199e70"
  },
  "viz-cat-4": {
    "light": "#4a3aa7",
    "dark": "#9085e9"
  },
  "viz-cat-5": {
    "light": "#008300",
    "dark": "#008300"
  },
  "viz-cat-6": {
    "light": "#e87ba4",
    "dark": "#d55181"
  },
  "viz-seq-1": {
    "light": "#cde2fb",
    "dark": "#0d366b"
  },
  "viz-seq-2": {
    "light": "#9ec5f4",
    "dark": "#184f95"
  },
  "viz-seq-3": {
    "light": "#6da7ec",
    "dark": "#256abf"
  },
  "viz-seq-4": {
    "light": "#3987e5",
    "dark": "#3987e5"
  },
  "viz-seq-5": {
    "light": "#256abf",
    "dark": "#6da7ec"
  },
  "viz-seq-6": {
    "light": "#184f95",
    "dark": "#9ec5f4"
  },
  "viz-seq-7": {
    "light": "#0d366b",
    "dark": "#cde2fb"
  },
  "viz-div-1": {
    "light": "#184f95",
    "dark": "#6da7ec"
  },
  "viz-div-2": {
    "light": "#3987e5",
    "dark": "#3987e5"
  },
  "viz-div-3": {
    "light": "#9ec5f4",
    "dark": "#184f95"
  },
  "viz-div-4": {
    "light": "#f0efec",
    "dark": "#383835"
  },
  "viz-div-5": {
    "light": "#feaa89",
    "dark": "#883001"
  },
  "viz-div-6": {
    "light": "#cf6335",
    "dark": "#cf6335"
  },
  "viz-div-7": {
    "light": "#883001",
    "dark": "#f08053"
  },
  "viz-grid": {
    "light": "#e1dfdb",
    "dark": "#272a2f"
  },
  "viz-axis": {
    "light": "#43484f",
    "dark": "#bdbab5"
  },
  "client-1": {
    "light": "#a0555c",
    "dark": "#efa8ac"
  },
  "client-2": {
    "light": "#6c2d0a",
    "dark": "#b87b60"
  },
  "client-3": {
    "light": "#2c5a21",
    "dark": "#7ca573"
  },
  "client-4": {
    "light": "#09816b",
    "dark": "#80d0bb"
  },
  "client-5": {
    "light": "#5e69a8",
    "dark": "#adbaf5"
  },
  "client-6": {
    "light": "#46376d",
    "dark": "#8f83b6"
  },
  "on-client": {
    "light": "#fefcf9",
    "dark": "#090b0f"
  },
  "shell": {
    "light": "#11151b",
    "dark": "#11151b"
  },
  "shell-ink": {
    "light": "#e8e6e1",
    "dark": "#e8e6e1"
  },
  "shell-strong": {
    "light": "#ffffff",
    "dark": "#ffffff"
  },
  "shell-item": {
    "light": "#b9bcc3",
    "dark": "#b9bcc3"
  },
  "shell-muted": {
    "light": "#8b8f97",
    "dark": "#8b8f97"
  },
  "shell-faint": {
    "light": "#7a7e87",
    "dark": "#7a7e87"
  },
  "shell-avatar": {
    "light": "#2a3140",
    "dark": "#2a3140"
  },
  "shell-avatar-ink": {
    "light": "#cfd6e4",
    "dark": "#cfd6e4"
  },
  "hue-blue": {
    "light": "#3557e0",
    "dark": "#3557e0"
  },
  "hue-teal": {
    "light": "#0f8a8a",
    "dark": "#0f8a8a"
  },
  "hue-orange": {
    "light": "#c26a1d",
    "dark": "#c26a1d"
  },
  "hue-violet": {
    "light": "#7a4fd6",
    "dark": "#7a4fd6"
  },
  "hue-green": {
    "light": "#1d9a6c",
    "dark": "#1d9a6c"
  },
  "hue-slate": {
    "light": "#5b6472",
    "dark": "#5b6472"
  },
  "shell-hue-blue": {
    "light": "#8aa2ff",
    "dark": "#8aa2ff"
  },
  "shell-hue-green": {
    "light": "#5fd1a5",
    "dark": "#5fd1a5"
  },
  "shell-hue-violet": {
    "light": "#b49aff",
    "dark": "#b49aff"
  },
  "shell-hue-slate": {
    "light": "#a9b0bb",
    "dark": "#a9b0bb"
  },
  "doc-paper": {
    "light": "#fffdfa",
    "dark": "#fffdfa"
  },
  "doc-ink": {
    "light": "#0f1216",
    "dark": "#0f1216"
  },
  "doc-muted": {
    "light": "#44484e",
    "dark": "#44484e"
  },
  "doc-rule": {
    "light": "#c6c4be",
    "dark": "#c6c4be"
  },
  "doc-accent": {
    "light": "#0d5279",
    "dark": "#0d5279"
  },
  "doc-wash": {
    "light": "#f3f1ec",
    "dark": "#f3f1ec"
  },
  "evidence-mark": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "evidence-hatch": {
    "light": "#5c6167",
    "dark": "#9e9b96"
  },
  "null-mark": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "suppressed-fill": {
    "light": "#43484f",
    "dark": "#bdbab5"
  },
  "budget-spent": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "budget-reserved": {
    "light": "#3557e0",
    "dark": "#8aa2ff"
  },
  "budget-uncertain": {
    "light": "#b52524",
    "dark": "#f47b74"
  },
  "scope-above": {
    "light": "#151a20",
    "dark": "#ece9e4"
  },
  "selection": {
    "light": "#e8edfd",
    "dark": "#1a2242"
  }
} as const;

export type ColorToken = keyof typeof colors;
export type Theme = "light" | "dark";

/** The CSS custom property for a colour token, e.g. cssVar("ink") → "var(--ink)". */
export function cssVar(name: ColorToken): string {
  return `var(--${name})`;
}

export const scalars = {
  "space-half": "2px",
  "space-1": "4px",
  "space-2": "8px",
  "space-3": "12px",
  "space-4": "16px",
  "space-6": "24px",
  "space-8": "32px",
  "space-12": "48px",
  "radius-0": "0px",
  "radius-sm": "2px",
  "radius-md": "4px",
  "radius-control": "6px",
  "radius-card": "8px",
  "radius-panel": "10px",
  "radius-pill": "999px",
  "stroke-hairline": "1px",
  "stroke-mark": "1.5px",
  "stroke-emphasis": "2px",
  "stroke-scope": "4px",
  "row-compact": "28px",
  "row-comfortable": "36px",
  "control-compact": "24px",
  "control-comfortable": "32px",
  "duration-instant": "0ms",
  "duration-confirm": "120ms",
  "duration-panel": "180ms",
  "z-scope": "30",
  "z-overlay": "40",
  "z-toast": "50"
} as const;
