"""Pure domain layer.

Nothing in this package may import a web framework, a database driver or an AI
provider SDK. It holds the rules that must stay true regardless of how the system
is deployed, so that they can be tested in isolation and reused by both the API
and the background workers.
"""

from .pipeline import (
    IMPACT_ROOTS,
    RESEARCH_STAGES,
    SIMULATION_STAGES,
    STAGE_EQUIVALENTS,
    ImpactPreview,
    ProjectType,
    StageStatus,
    changed_fields,
    fingerprint,
    impact_preview,
    resolve_stage,
    stage_fingerprint,
    stage_ids,
    stage_input_payload,
    stage_labels,
    stages_for,
)
from .project import (
    Project,
    ProjectRevision,
    ProjectStatus,
    SaveOutcome,
    StageState,
    carry_forward_stages,
    initial_stages,
    new_project_id,
    new_revision_id,
    plan_save,
    resolve_provider_defaults,
)
from .providers import (
    DEFAULT_MAX_API_COST_USD,
    BudgetDecision,
    ModelRole,
    Provider,
    ProviderPolicy,
    check_budget,
    is_paid,
    normalize_policy,
    normalize_provider,
    policy_for_provider,
    provider_for_stage,
    ui_label,
)

__all__ = [
    "DEFAULT_MAX_API_COST_USD",
    "IMPACT_ROOTS",
    "RESEARCH_STAGES",
    "SIMULATION_STAGES",
    "STAGE_EQUIVALENTS",
    "BudgetDecision",
    "ImpactPreview",
    "ModelRole",
    "Project",
    "ProjectRevision",
    "ProjectStatus",
    "ProjectType",
    "Provider",
    "ProviderPolicy",
    "SaveOutcome",
    "StageState",
    "StageStatus",
    "carry_forward_stages",
    "changed_fields",
    "check_budget",
    "fingerprint",
    "impact_preview",
    "initial_stages",
    "is_paid",
    "new_project_id",
    "new_revision_id",
    "normalize_policy",
    "normalize_provider",
    "plan_save",
    "policy_for_provider",
    "provider_for_stage",
    "resolve_provider_defaults",
    "resolve_stage",
    "stage_fingerprint",
    "stage_ids",
    "stage_input_payload",
    "stage_labels",
    "stages_for",
    "ui_label",
]
