#!/usr/bin/env python3
"""Compute parity verdicts from the parity matrix and a run's test results.

The matrix (``docs/migration/parity-matrix.json``) *declares* what establishes
parity for each of the 78 reference capabilities: its gates, the tests in each
gate, and the environment each gate needs. It never stores a verdict. This tool
derives one from pytest JUnit XML, so a verdict is always a statement about a
specific run:

    PASS          every gate executed and passed, and the gates that exist are
                  enough to establish this parity type
    FAIL          a gate executed and failed -- or, with --available, a gate
                  whose environment was present did not execute at all
    NOT_EXECUTED  the gates exist but did not run here (skipped, or not
                  collected). A skip is never a pass.
    NOT_RUNNABLE  no gate exists that could establish parity: nothing ported,
                  a fixture still ungated, or only production-only tests for a
                  type that needs the reference
    NOT_REQUIRED  the capability owes no parity

Stdlib only, like the rest of ``tools/``: a checker that needs its own toolchain
gets disabled the first time that toolchain breaks.

    python tools/parity_status.py                       # declared picture, no run
    python tools/parity_status.py --junit a.xml b.xml \\
        --available postgres reference_repo \\
        --json parity-status.json --markdown parity-status.md
    python tools/parity_status.py render --write docs/migration/parity-matrix.md

Exit status: 1 when any capability is FAIL or the matrix is malformed, else 0.
NOT_EXECUTED and NOT_RUNNABLE do not fail the run -- they are reported, loudly,
and CI's step summary shows them next to the passes so nobody mistakes one for
the other.
"""

from __future__ import annotations

import argparse
import json
import sys
import xml.etree.ElementTree as ET
from collections import Counter
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
DEFAULT_MATRIX = REPO / "docs" / "migration" / "parity-matrix.json"

PASS = "PASS"
FAIL = "FAIL"
NOT_EXECUTED = "NOT_EXECUTED"
NOT_RUNNABLE = "NOT_RUNNABLE"
NOT_REQUIRED = "NOT_REQUIRED"
VERDICTS = (FAIL, NOT_RUNNABLE, NOT_EXECUTED, PASS, NOT_REQUIRED)

REFERENCE_BACKED = frozenset(
    {"reference_comparison", "reference_characterization", "reference_contract", "golden_fixture"}
)
PARITY_WEIGHT = {"EXACT": 0, "NUMERICAL": 1, "INTENTIONAL_DIFFERENCE": 2, "SEMANTIC": 3}
NO_RISK_RANK = 99

TABLE_BEGIN = "<!-- parity-matrix:begin (generated by tools/parity_status.py render) -->"
TABLE_END = "<!-- parity-matrix:end -->"


# --------------------------------------------------------------------------- #
# Test results
# --------------------------------------------------------------------------- #

PASSED = "passed"
FAILED = "failed"
SKIPPED = "skipped"
_OUTCOME_RANK = {FAILED: 0, PASSED: 1, SKIPPED: 2}


@dataclass(frozen=True)
class TestCase:
    """One test outcome from a JUnit file. ``file`` is relative to pytest's rootdir."""

    file: str
    name: str
    outcome: str


def _module_file_from_classname(classname: str) -> tuple[str, str]:
    """Recover ``(file, class_path)`` from an xunit2 classname.

    ``packages.aia_core.tests.test_x.TestThing`` -> ``packages/aia_core/tests/test_x.py``,
    ``TestThing``. The module is the last dotted component starting ``test_``.
    """
    parts = classname.split(".")
    for i in range(len(parts) - 1, -1, -1):
        if parts[i].startswith("test_"):
            return "/".join(parts[: i + 1]) + ".py", "::".join(parts[i + 1 :])
    return "/".join(parts) + ".py", ""


def parse_junit(path: Path) -> list[TestCase]:
    """Read one JUnit XML file (xunit1 or xunit2) into test outcomes."""
    cases: list[TestCase] = []
    for case in ET.parse(path).getroot().iter("testcase"):
        classname = case.get("classname", "")
        derived_file, class_path = _module_file_from_classname(classname)
        file = case.get("file") or derived_file
        name = case.get("name", "")
        if class_path:
            name = f"{class_path}::{name}"
        if case.find("failure") is not None or case.find("error") is not None:
            outcome = FAILED
        elif case.find("skipped") is not None:
            outcome = SKIPPED
        else:
            outcome = PASSED
        cases.append(TestCase(file=file.replace("\\", "/"), name=name, outcome=outcome))
    return cases


def merge_results(cases: Iterable[TestCase]) -> dict[tuple[str, str], str]:
    """Merge outcomes across runs: a failure anywhere wins, then any pass.

    The same test runs on PostgreSQL and on SQLite; passing on one and skipping
    on the other is a pass, failing on either is a failure.
    """
    merged: dict[tuple[str, str], str] = {}
    for case in cases:
        key = (case.file, case.name)
        current = merged.get(key)
        if current is None or _OUTCOME_RANK[case.outcome] < _OUTCOME_RANK[current]:
            merged[key] = case.outcome
    return merged


def _same_file(declared: str, reported: str) -> bool:
    """Match a repository-relative path against a rootdir-relative one.

    pytest reports paths relative to whichever ``pyproject.toml`` it chose as
    rootdir -- ``tests/test_x.py`` when run as ``pytest packages/aia_core``,
    ``packages/aia_core/tests/test_x.py`` when run from the root.
    """
    return declared == reported or declared.endswith("/" + reported)


def matching_outcomes(pattern: str, results: Mapping[tuple[str, str], str]) -> list[str]:
    """Outcomes of every test a gate pattern names.

    A pattern is ``path/test_file.py`` (the whole module) or
    ``path/test_file.py::test_name`` (that test and all its parametrizations).

    One test can appear under two rootdir-relative paths -- the SQLite step runs
    from the repository root, the PostgreSQL steps from the package -- so
    outcomes are merged per test *name* after path matching, not per reported
    path: passed on PostgreSQL and skipped on SQLite is one pass.
    """
    path, _, name = pattern.partition("::")
    found: dict[str, str] = {}
    for (file, case), outcome in results.items():
        if not _same_file(path, file):
            continue
        if not name or case == name or case.startswith(name + "["):
            current = found.get(case)
            if current is None or _OUTCOME_RANK[outcome] < _OUTCOME_RANK[current]:
                found[case] = outcome
    return list(found.values())


# --------------------------------------------------------------------------- #
# Verdicts
# --------------------------------------------------------------------------- #


@dataclass
class GateResult:
    id: str
    kind: str
    requires: list[str]
    verdict: str
    passed: int = 0
    failed: int = 0
    skipped: int = 0
    detail: str = ""


@dataclass
class CapabilityStatus:
    id: str
    owner: str
    owner_confirmed: bool
    implementation_state: str
    parity_type: str
    verdict: str
    release_blocker: bool
    release_ready: bool
    high_risk: list[str]
    gates: list[GateResult] = field(default_factory=list)
    missing: list[str] = field(default_factory=list)
    detail: str = ""


def evaluate_gate(
    gate: Mapping[str, Any],
    results: Mapping[tuple[str, str], str] | None,
    available: frozenset[str] | None,
) -> GateResult:
    """Decide one gate from test outcomes.

    ``results is None`` means no run was supplied: nothing executed. With
    ``available`` given, a gate whose every requirement was present in this run
    but which did not execute is a FAIL -- it should have run, and a renamed or
    deselected test must not read as "environment absent".
    """
    out = GateResult(
        id=str(gate["id"]),
        kind=str(gate["kind"]),
        requires=list(gate["requires"]),
        verdict=NOT_EXECUTED,
    )
    if results is None:
        out.detail = "no test results supplied"
        return out
    uncollected: list[str] = []
    for pattern in gate["tests"]:
        outcomes = matching_outcomes(str(pattern), results)
        if not outcomes:
            uncollected.append(str(pattern))
        counts = Counter(outcomes)
        out.passed += counts[PASSED]
        out.failed += counts[FAILED]
        out.skipped += counts[SKIPPED]
    if out.failed:
        out.verdict = FAIL
        out.detail = f"{out.failed} test(s) failed"
    elif not uncollected and not out.skipped:
        out.verdict = PASS
    else:
        reasons = []
        if out.skipped:
            reasons.append(f"{out.skipped} skipped")
        if uncollected:
            reasons.append(f"{len(uncollected)} pattern(s) not collected")
        out.detail = ", ".join(reasons)
        if available is not None and set(out.requires) <= available:
            out.verdict = FAIL
            out.detail += "; its environment was available, so it should have run"
    return out


def evaluate_capability(
    cid: str,
    cap: Mapping[str, Any],
    fixtures: Mapping[str, Mapping[str, Any]],
    results: Mapping[tuple[str, str], str] | None,
    available: frozenset[str] | None,
) -> CapabilityStatus:
    status = CapabilityStatus(
        id=cid,
        owner=str(cap["owner"]["workstream"]),
        owner_confirmed=bool(cap["owner"]["confirmed"]),
        implementation_state=str(cap["implementation_state"]),
        parity_type=str(cap["parity_type"]),
        verdict=NOT_REQUIRED,
        release_blocker=bool(cap["release_blocker"]["blocking"]),
        release_ready=False,
        high_risk=list(cap["high_risk"]),
    )
    if status.parity_type == "NO_PARITY_REQUIRED":
        status.detail = "owes no parity"
        return status

    status.gates = [evaluate_gate(g, results, available) for g in cap["gates"]]
    for fid in cap["fixtures"]:
        fx = fixtures[fid]
        if fx["gates_capability"] and fx["gate"]["state"] != "GATED":
            status.missing.append(f"{fid}: {fx['gate']['state']}")
    kinds = {g.kind for g in status.gates}
    if status.parity_type == "INTENTIONAL_DIFFERENCE":
        if "production_contract" not in kinds:
            status.missing.append("no production test proving the new behaviour")
    elif not kinds & REFERENCE_BACKED:
        status.missing.append("no reference-backed gate")

    verdicts = {g.verdict for g in status.gates}
    if FAIL in verdicts:
        status.verdict = FAIL
        status.detail = "; ".join(f"{g.id}: {g.detail}" for g in status.gates if g.verdict == FAIL)
    elif status.missing:
        status.verdict = NOT_RUNNABLE
        status.detail = "; ".join(status.missing)
    elif NOT_EXECUTED in verdicts:
        status.verdict = NOT_EXECUTED
        status.detail = "; ".join(
            f"{g.id}: {g.detail}" for g in status.gates if g.verdict == NOT_EXECUTED
        )
    else:
        status.verdict = PASS
    status.release_ready = status.verdict == PASS and status.implementation_state == "IMPLEMENTED"
    return status


def _risk_rank(high_risk: Sequence[str]) -> int:
    """R1 is the highest-consequence behaviour; the reference orders them so."""
    return min((int(r[1:]) for r in high_risk), default=NO_RISK_RANK)


def rank_unverified(statuses: Iterable[CapabilityStatus]) -> list[CapabilityStatus]:
    """Order the capabilities that are not release-ready, riskiest first.

    A failed gate outranks everything. Then release blockers. Then anything
    whose gates do not pass -- a capability whose existing gates all pass but
    whose implementation is unfinished is incomplete, not unverified. Then code
    that already exists -- an unverified port can ship; an unstarted one cannot.
    Then the highest-consequence high-risk behaviour, then the strictest parity
    type.
    """
    candidates = [s for s in statuses if s.verdict != NOT_REQUIRED and not s.release_ready]

    def key(s: CapabilityStatus) -> tuple[int, int, int, int, int, int, str]:
        return (
            0 if s.verdict == FAIL else 1,
            0 if s.release_blocker else 1,
            1 if s.verdict == PASS else 0,
            0 if s.implementation_state in {"IMPLEMENTED", "PARTIAL"} else 1,
            _risk_rank(s.high_risk),
            PARITY_WEIGHT.get(s.parity_type, 9),
            s.id,
        )

    return sorted(candidates, key=key)


def why_risky(s: CapabilityStatus) -> str:
    parts = [f"{s.implementation_state}", f"{s.parity_type} parity", f"verdict {s.verdict}"]
    if s.high_risk:
        parts.append("high-risk " + "/".join(s.high_risk))
    if s.release_blocker:
        parts.append("MVP release blocker")
    text = ", ".join(parts)
    return f"{text} -- {s.detail}" if s.detail else text


@dataclass
class Report:
    reference_commit: str
    results_supplied: bool
    available: list[str] | None
    counts: dict[str, int]
    blocking_counts: dict[str, int]
    capabilities: list[CapabilityStatus]
    highest_risk_unverified: list[str]
    unowned: list[str]
    acceptance: dict[str, Any]
    fixtures: list[dict[str, Any]]

    def failed(self) -> bool:
        return self.counts.get(FAIL, 0) > 0

    def to_json(self) -> dict[str, Any]:
        return asdict(self)


def build_report(
    matrix: Mapping[str, Any],
    results: Mapping[tuple[str, str], str] | None,
    available: frozenset[str] | None,
) -> Report:
    fixtures: Mapping[str, Mapping[str, Any]] = matrix["fixtures"]
    statuses = [
        evaluate_capability(cid, cap, fixtures, results, available)
        for cid, cap in sorted(matrix["capabilities"].items())
    ]
    by_id = {s.id: s for s in statuses}
    ranked = rank_unverified(statuses)

    acceptance = matrix["mvp_acceptance"]
    on_path = sorted(s.id for s in statuses if s.release_blocker)
    not_ready = [cid for cid in on_path if not by_id[cid].release_ready]
    acceptance_verdict = NOT_RUNNABLE if acceptance["test"] is None or not_ready else NOT_EXECUTED

    gate_verdicts = {g.id: g.verdict for s in statuses for g in s.gates}
    fixture_rows = []
    for fid, fx in sorted(fixtures.items()):
        gate_verdict = gate_verdicts.get(fx["gate"].get("gate_id") or "")
        fixture_rows.append(
            {
                "fixture": fid,
                "capability": fx["capability"],
                "status": fx["status"],
                "source": fx.get("source"),
                "gate_state": fx["gate"]["state"],
                "verdict": gate_verdict or NOT_RUNNABLE,
                "ci_runnable": fx["status"] == "CAPTURED"
                and set(fx["requires"]) <= {"reference_repo"},
                "gap": fx["gap"],
            }
        )

    return Report(
        reference_commit=str(matrix["reference"]["commit"]),
        results_supplied=results is not None,
        available=sorted(available) if available is not None else None,
        counts=dict(Counter(s.verdict for s in statuses)),
        blocking_counts=dict(Counter(s.verdict for s in statuses if s.release_blocker)),
        capabilities=statuses,
        highest_risk_unverified=[f"{s.id}: {why_risky(s)}" for s in ranked[:5]],
        unowned=sorted(s.id for s in statuses if not s.owner_confirmed),
        acceptance={
            "id": acceptance["id"],
            "verdict": acceptance_verdict,
            "test": acceptance["test"],
            "capabilities_on_path": len(on_path),
            "not_release_ready": len(not_ready),
            "not_release_ready_by_state": dict(
                Counter(by_id[c].implementation_state for c in not_ready)
            ),
        },
        fixtures=fixture_rows,
    )


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #


def render_report_markdown(report: Report) -> str:
    lines = ["## Parity status", ""]
    if not report.results_supplied:
        lines += [
            "> **No test results were supplied.** Every gate below is `NOT_EXECUTED` by",
            "> definition; this is the declared picture, not evidence.",
            "",
        ]
    lines += [f"Reference pinned at `{report.reference_commit}`.", ""]
    lines += ["| Verdict | All | MVP blockers |", "| --- | ---: | ---: |"]
    for verdict in VERDICTS:
        lines.append(
            f"| `{verdict}` | {report.counts.get(verdict, 0)} "
            f"| {report.blocking_counts.get(verdict, 0)} |"
        )
    lines += ["", "### Highest-risk unverified capability", ""]
    if report.highest_risk_unverified:
        top, *rest = report.highest_risk_unverified
        lines += [f"**{top}**", ""]
        lines += [f"{i}. {item}" for i, item in enumerate(rest, start=2)]
    else:
        lines.append("None: every parity-bearing capability is release-ready.")
    acc = report.acceptance
    lines += [
        "",
        f"### {acc['id']} — MVP acceptance test",
        "",
        f"`{acc['verdict']}`. {acc['not_release_ready']} of {acc['capabilities_on_path']} "
        "capabilities on the acceptance path are not release-ready "
        f"({', '.join(f'{k} {v}' for k, v in sorted(acc['not_release_ready_by_state'].items()))}).",
        "",
        "### Golden fixtures",
        "",
        "| Fixture | Capability | Source | Gate | Verdict | Runs in CI | Gap |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in report.fixtures:
        lines.append(
            f"| `{row['fixture']}` | `{row['capability']}` | {row['source'] or row['status']} "
            f"| {row['gate_state']} | `{row['verdict']}` "
            f"| {'yes' if row['ci_runnable'] else 'no'} | {row['gap'] or ''} |"
        )
    lines += [
        "",
        "### Capabilities",
        "",
        "| Capability | Owner | State | Parity | Verdict | Gates passed | Detail |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for s in report.capabilities:
        if s.verdict == NOT_REQUIRED:
            continue
        passed = sum(1 for g in s.gates if g.verdict == PASS)
        owner = s.owner if s.owner_confirmed else f"{s.owner} *(unconfirmed)*"
        blocker = " **B**" if s.release_blocker else ""
        lines.append(
            f"| `{s.id}`{blocker} | {owner} | {s.implementation_state} | {s.parity_type} "
            f"| `{s.verdict}` | {passed}/{len(s.gates)} | {s.detail} |"
        )
    lines += [
        "",
        f"**B** = MVP release blocker. {len(report.unowned)} capabilities have no confirmed owner.",
        "",
    ]
    return "\n".join(lines)


def render_table(matrix: Mapping[str, Any]) -> str:
    """The declared matrix as markdown, for ``parity-matrix.md``. No verdicts."""
    lines = [
        TABLE_BEGIN,
        "",
        "| Capability | Owner | State | Parity | Tolerance | Fixtures | Gates | High risk "
        "| MVP blocker |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for cid, cap in sorted(matrix["capabilities"].items()):
        owner = cap["owner"]["workstream"] + (
            "" if cap["owner"]["confirmed"] else " *(unconfirmed)*"
        )
        fixtures = ", ".join(f.split("_", 1)[0] for f in cap["fixtures"]) or "—"
        kinds = Counter(g["kind"] for g in cap["gates"])
        gates = ", ".join(f"{k} x{n}" for k, n in sorted(kinds.items())) or "—"
        tol = "—" if cap["tolerance"] is None else f"`{cap['tolerance']:g}`"
        lines.append(
            f"| `{cid}` | {owner} | {cap['implementation_state']} | {cap['parity_type']} "
            f"| {tol} | {fixtures} | {gates} | {', '.join(cap['high_risk']) or '—'} "
            f"| {'yes' if cap['release_blocker']['blocking'] else 'no'} |"
        )
    lines += ["", TABLE_END]
    return "\n".join(lines)


def splice_table(document: str, table: str) -> str:
    """Replace the generated section of ``document`` with ``table``."""
    start = document.index(TABLE_BEGIN)
    end = document.index(TABLE_END) + len(TABLE_END)
    return document[:start] + table + document[end:]


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def load_matrix(path: Path) -> dict[str, Any]:
    data: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    for key in ("reference", "fixtures", "capabilities", "mvp_acceptance"):
        if key not in data:
            raise SystemExit(f"{path}: malformed parity matrix, missing {key!r}")
    return data


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("command", nargs="?", default="report", choices=["report", "render"])
    parser.add_argument("--matrix", type=Path, default=DEFAULT_MATRIX)
    parser.add_argument("--junit", type=Path, nargs="*", default=None, help="pytest JUnit XML")
    parser.add_argument(
        "--available",
        nargs="*",
        default=None,
        help="environments present in this run (postgres, reference_repo, legacy_tree, ...); "
        "a gate needing only these that did not execute is a FAIL",
    )
    parser.add_argument("--json", type=Path, help="write the full report as JSON")
    parser.add_argument("--markdown", type=Path, help="write the report as markdown")
    parser.add_argument("--write", type=Path, help="render: splice the table into this file")
    args = parser.parse_args(argv)

    matrix = load_matrix(args.matrix)

    if args.command == "render":
        table = render_table(matrix)
        if args.write:
            args.write.write_text(splice_table(args.write.read_text("utf-8"), table), "utf-8")
            print(f"wrote the capability table into {args.write}")
        else:
            print(table)
        return 0

    results = None
    if args.junit is not None:
        cases: list[TestCase] = []
        for path in args.junit:
            if path.is_file():
                cases.extend(parse_junit(path))
            else:
                print(f"warning: {path} does not exist; its tests count as not executed")
        results = merge_results(cases)
    available = frozenset(args.available) if args.available is not None else None

    report = build_report(matrix, results, available)
    markdown = render_report_markdown(report)
    if args.json:
        args.json.write_text(json.dumps(report.to_json(), indent=2) + "\n", "utf-8")
    if args.markdown:
        args.markdown.write_text(markdown, "utf-8")

    print(f"parity status @ reference {report.reference_commit[:12]}")
    for verdict in VERDICTS:
        print(
            f"  {verdict:<13} {report.counts.get(verdict, 0):>3}"
            f"   (MVP blockers {report.blocking_counts.get(verdict, 0)})"
        )
    if report.highest_risk_unverified:
        print(f"highest-risk unverified: {report.highest_risk_unverified[0]}")
    acc = report.acceptance
    print(
        f"{acc['id']}: {acc['verdict']} -- {acc['not_release_ready']} of "
        f"{acc['capabilities_on_path']} capabilities on the path are not release-ready"
    )
    if report.failed():
        print("parity_status: FAILED -- a parity gate failed or did not run where it could.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
